// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/repository/tinybird (interfaces: EmailRepositoryInterface,ActivityRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_tinybird.go -package=mocks github.com/emailapi/api/internal/repository/tinybird EmailRepositoryInterface,ActivityRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	tinybird "github.com/emailapi/api/internal/repository/tinybird"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailRepositoryInterface is a mock of EmailRepositoryInterface interface.
type MockEmailRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEmailRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockEmailRepositoryInterfaceMockRecorder is the mock recorder for MockEmailRepositoryInterface.
type MockEmailRepositoryInterfaceMockRecorder struct {
	mock *MockEmailRepositoryInterface
}

// NewMockEmailRepositoryInterface creates a new mock instance.
func NewMockEmailRepositoryInterface(ctrl *gomock.Controller) *MockEmailRepositoryInterface {
	mock := &MockEmailRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockEmailRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailRepositoryInterface) EXPECT() *MockEmailRepositoryInterfaceMockRecorder {
	return m.recorder
}

// InsertRouting mocks base method.
func (m *MockEmailRepositoryInterface) InsertRouting(ctx context.Context, messageID, emailID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRouting", ctx, messageID, emailID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRouting indicates an expected call of InsertRouting.
func (mr *MockEmailRepositoryInterfaceMockRecorder) InsertRouting(ctx, messageID, emailID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRouting", reflect.TypeOf((*MockEmailRepositoryInterface)(nil).InsertRouting), ctx, messageID, emailID, userID)
}

// LogActivity mocks base method.
func (m *MockEmailRepositoryInterface) LogActivity(ctx context.Context, userID, entityType, entityID, action, status, details string, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogActivity", ctx, userID, entityType, entityID, action, status, details, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogActivity indicates an expected call of LogActivity.
func (mr *MockEmailRepositoryInterfaceMockRecorder) LogActivity(ctx, userID, entityType, entityID, action, status, details, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogActivity", reflect.TypeOf((*MockEmailRepositoryInterface)(nil).LogActivity), ctx, userID, entityType, entityID, action, status, details, metadata)
}

// LogEmailEvent mocks base method.
func (m *MockEmailRepositoryInterface) LogEmailEvent(ctx context.Context, userID, emailID, action, status, details string, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogEmailEvent", ctx, userID, emailID, action, status, details, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogEmailEvent indicates an expected call of LogEmailEvent.
func (mr *MockEmailRepositoryInterfaceMockRecorder) LogEmailEvent(ctx, userID, emailID, action, status, details, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogEmailEvent", reflect.TypeOf((*MockEmailRepositoryInterface)(nil).LogEmailEvent), ctx, userID, emailID, action, status, details, metadata)
}

// LookupRouting mocks base method.
func (m *MockEmailRepositoryInterface) LookupRouting(ctx context.Context, messageID string) (*tinybird.EmailRouting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupRouting", ctx, messageID)
	ret0, _ := ret[0].(*tinybird.EmailRouting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupRouting indicates an expected call of LookupRouting.
func (mr *MockEmailRepositoryInterfaceMockRecorder) LookupRouting(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupRouting", reflect.TypeOf((*MockEmailRepositoryInterface)(nil).LookupRouting), ctx, messageID)
}

// LookupRoutingByEmailID mocks base method.
func (m *MockEmailRepositoryInterface) LookupRoutingByEmailID(ctx context.Context, emailID string) (*tinybird.EmailRouting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupRoutingByEmailID", ctx, emailID)
	ret0, _ := ret[0].(*tinybird.EmailRouting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupRoutingByEmailID indicates an expected call of LookupRoutingByEmailID.
func (mr *MockEmailRepositoryInterfaceMockRecorder) LookupRoutingByEmailID(ctx, emailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupRoutingByEmailID", reflect.TypeOf((*MockEmailRepositoryInterface)(nil).LookupRoutingByEmailID), ctx, emailID)
}

// Ping mocks base method.
func (m *MockEmailRepositoryInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockEmailRepositoryInterfaceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockEmailRepositoryInterface)(nil).Ping), ctx)
}

// MockActivityRepositoryInterface is a mock of ActivityRepositoryInterface interface.
type MockActivityRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockActivityRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockActivityRepositoryInterfaceMockRecorder is the mock recorder for MockActivityRepositoryInterface.
type MockActivityRepositoryInterfaceMockRecorder struct {
	mock *MockActivityRepositoryInterface
}

// NewMockActivityRepositoryInterface creates a new mock instance.
func NewMockActivityRepositoryInterface(ctrl *gomock.Controller) *MockActivityRepositoryInterface {
	mock := &MockActivityRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockActivityRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityRepositoryInterface) EXPECT() *MockActivityRepositoryInterfaceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockActivityRepositoryInterface) List(ctx context.Context, userID string, filters tinybird.ActivityFilters, limit, offset int) ([]tinybird.ActivityLog, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, filters, limit, offset)
	ret0, _ := ret[0].([]tinybird.ActivityLog)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockActivityRepositoryInterfaceMockRecorder) List(ctx, userID, filters, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).List), ctx, userID, filters, limit, offset)
}

// Log mocks base method.
func (m *MockActivityRepositoryInterface) Log(ctx context.Context, userID, entityType, entityID, action, status, details string, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", ctx, userID, entityType, entityID, action, status, details, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// Log indicates an expected call of Log.
func (mr *MockActivityRepositoryInterfaceMockRecorder) Log(ctx, userID, entityType, entityID, action, status, details, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).Log), ctx, userID, entityType, entityID, action, status, details, metadata)
}

// LogAPIKey mocks base method.
func (m *MockActivityRepositoryInterface) LogAPIKey(ctx context.Context, userID, apiKeyID, action, status, details string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAPIKey", ctx, userID, apiKeyID, action, status, details)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogAPIKey indicates an expected call of LogAPIKey.
func (mr *MockActivityRepositoryInterfaceMockRecorder) LogAPIKey(ctx, userID, apiKeyID, action, status, details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAPIKey", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).LogAPIKey), ctx, userID, apiKeyID, action, status, details)
}

// LogDomain mocks base method.
func (m *MockActivityRepositoryInterface) LogDomain(ctx context.Context, userID, domainID, action, status, details string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogDomain", ctx, userID, domainID, action, status, details)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogDomain indicates an expected call of LogDomain.
func (mr *MockActivityRepositoryInterfaceMockRecorder) LogDomain(ctx, userID, domainID, action, status, details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogDomain", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).LogDomain), ctx, userID, domainID, action, status, details)
}

// LogEmail mocks base method.
func (m *MockActivityRepositoryInterface) LogEmail(ctx context.Context, userID, emailID, action, status, details string, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogEmail", ctx, userID, emailID, action, status, details, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogEmail indicates an expected call of LogEmail.
func (mr *MockActivityRepositoryInterfaceMockRecorder) LogEmail(ctx, userID, emailID, action, status, details, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogEmail", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).LogEmail), ctx, userID, emailID, action, status, details, metadata)
}

// Ping mocks base method.
func (m *MockActivityRepositoryInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockActivityRepositoryInterfaceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).Ping), ctx)
}
