// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/events/handlers (interfaces: Analytics,ActivityLogger,EmailRouter,SuppressionManager,ReputationRecorder,InboundEmailProcessor)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_handlers.go -package=mocks github.com/emailapi/api/internal/events/handlers Analytics,ActivityLogger,EmailRouter,SuppressionManager,ReputationRecorder,InboundEmailProcessor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/emailapi/api/internal/domain"
	handlers "github.com/emailapi/api/internal/events/handlers"
	suppression "github.com/emailapi/api/internal/repository/suppression"
	tinybird "github.com/emailapi/api/internal/repository/tinybird"
	gomock "go.uber.org/mock/gomock"
)

// MockAnalytics is a mock of Analytics interface.
type MockAnalytics struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsMockRecorder
	isgomock struct{}
}

// MockAnalyticsMockRecorder is the mock recorder for MockAnalytics.
type MockAnalyticsMockRecorder struct {
	mock *MockAnalytics
}

// NewMockAnalytics creates a new mock instance.
func NewMockAnalytics(ctrl *gomock.Controller) *MockAnalytics {
	mock := &MockAnalytics{ctrl: ctrl}
	mock.recorder = &MockAnalyticsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalytics) EXPECT() *MockAnalyticsMockRecorder {
	return m.recorder
}

// Activity mocks base method.
func (m *MockAnalytics) Activity() handlers.ActivityLogger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activity")
	ret0, _ := ret[0].(handlers.ActivityLogger)
	return ret0
}

// Activity indicates an expected call of Activity.
func (mr *MockAnalyticsMockRecorder) Activity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activity", reflect.TypeOf((*MockAnalytics)(nil).Activity))
}

// Email mocks base method.
func (m *MockAnalytics) Email() handlers.EmailRouter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Email")
	ret0, _ := ret[0].(handlers.EmailRouter)
	return ret0
}

// Email indicates an expected call of Email.
func (mr *MockAnalyticsMockRecorder) Email() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Email", reflect.TypeOf((*MockAnalytics)(nil).Email))
}

// MockActivityLogger is a mock of ActivityLogger interface.
type MockActivityLogger struct {
	ctrl     *gomock.Controller
	recorder *MockActivityLoggerMockRecorder
	isgomock struct{}
}

// MockActivityLoggerMockRecorder is the mock recorder for MockActivityLogger.
type MockActivityLoggerMockRecorder struct {
	mock *MockActivityLogger
}

// NewMockActivityLogger creates a new mock instance.
func NewMockActivityLogger(ctrl *gomock.Controller) *MockActivityLogger {
	mock := &MockActivityLogger{ctrl: ctrl}
	mock.recorder = &MockActivityLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityLogger) EXPECT() *MockActivityLoggerMockRecorder {
	return m.recorder
}

// Log mocks base method.
func (m *MockActivityLogger) Log(ctx context.Context, userID, entityType, entityID, action, status, message string, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", ctx, userID, entityType, entityID, action, status, message, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// Log indicates an expected call of Log.
func (mr *MockActivityLoggerMockRecorder) Log(ctx, userID, entityType, entityID, action, status, message, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockActivityLogger)(nil).Log), ctx, userID, entityType, entityID, action, status, message, metadata)
}

// MockEmailRouter is a mock of EmailRouter interface.
type MockEmailRouter struct {
	ctrl     *gomock.Controller
	recorder *MockEmailRouterMockRecorder
	isgomock struct{}
}

// MockEmailRouterMockRecorder is the mock recorder for MockEmailRouter.
type MockEmailRouterMockRecorder struct {
	mock *MockEmailRouter
}

// NewMockEmailRouter creates a new mock instance.
func NewMockEmailRouter(ctrl *gomock.Controller) *MockEmailRouter {
	mock := &MockEmailRouter{ctrl: ctrl}
	mock.recorder = &MockEmailRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailRouter) EXPECT() *MockEmailRouterMockRecorder {
	return m.recorder
}

// LookupRouting mocks base method.
func (m *MockEmailRouter) LookupRouting(ctx context.Context, messageID string) (*tinybird.EmailRouting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupRouting", ctx, messageID)
	ret0, _ := ret[0].(*tinybird.EmailRouting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupRouting indicates an expected call of LookupRouting.
func (mr *MockEmailRouterMockRecorder) LookupRouting(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupRouting", reflect.TypeOf((*MockEmailRouter)(nil).LookupRouting), ctx, messageID)
}

// MockSuppressionManager is a mock of SuppressionManager interface.
type MockSuppressionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSuppressionManagerMockRecorder
	isgomock struct{}
}

// MockSuppressionManagerMockRecorder is the mock recorder for MockSuppressionManager.
type MockSuppressionManagerMockRecorder struct {
	mock *MockSuppressionManager
}

// NewMockSuppressionManager creates a new mock instance.
func NewMockSuppressionManager(ctrl *gomock.Controller) *MockSuppressionManager {
	mock := &MockSuppressionManager{ctrl: ctrl}
	mock.recorder = &MockSuppressionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuppressionManager) EXPECT() *MockSuppressionManagerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockSuppressionManager) Add(ctx context.Context, entry *suppression.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockSuppressionManagerMockRecorder) Add(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockSuppressionManager)(nil).Add), ctx, entry)
}

// MockReputationRecorder is a mock of ReputationRecorder interface.
type MockReputationRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockReputationRecorderMockRecorder
	isgomock struct{}
}

// MockReputationRecorderMockRecorder is the mock recorder for MockReputationRecorder.
type MockReputationRecorderMockRecorder struct {
	mock *MockReputationRecorder
}

// NewMockReputationRecorder creates a new mock instance.
func NewMockReputationRecorder(ctrl *gomock.Controller) *MockReputationRecorder {
	mock := &MockReputationRecorder{ctrl: ctrl}
	mock.recorder = &MockReputationRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReputationRecorder) EXPECT() *MockReputationRecorderMockRecorder {
	return m.recorder
}

// RecordBounceIncident mocks base method.
func (m *MockReputationRecorder) RecordBounceIncident(ctx context.Context, userID, messageID, bounceType, bounceSubType string, recipients []domain.BounceRecipient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordBounceIncident", ctx, userID, messageID, bounceType, bounceSubType, recipients)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordBounceIncident indicates an expected call of RecordBounceIncident.
func (mr *MockReputationRecorderMockRecorder) RecordBounceIncident(ctx, userID, messageID, bounceType, bounceSubType, recipients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordBounceIncident", reflect.TypeOf((*MockReputationRecorder)(nil).RecordBounceIncident), ctx, userID, messageID, bounceType, bounceSubType, recipients)
}

// RecordComplaintIncident mocks base method.
func (m *MockReputationRecorder) RecordComplaintIncident(ctx context.Context, userID, messageID, feedbackType string, recipients []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordComplaintIncident", ctx, userID, messageID, feedbackType, recipients)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordComplaintIncident indicates an expected call of RecordComplaintIncident.
func (mr *MockReputationRecorderMockRecorder) RecordComplaintIncident(ctx, userID, messageID, feedbackType, recipients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordComplaintIncident", reflect.TypeOf((*MockReputationRecorder)(nil).RecordComplaintIncident), ctx, userID, messageID, feedbackType, recipients)
}

// MockInboundEmailProcessor is a mock of InboundEmailProcessor interface.
type MockInboundEmailProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockInboundEmailProcessorMockRecorder
	isgomock struct{}
}

// MockInboundEmailProcessorMockRecorder is the mock recorder for MockInboundEmailProcessor.
type MockInboundEmailProcessorMockRecorder struct {
	mock *MockInboundEmailProcessor
}

// NewMockInboundEmailProcessor creates a new mock instance.
func NewMockInboundEmailProcessor(ctrl *gomock.Controller) *MockInboundEmailProcessor {
	mock := &MockInboundEmailProcessor{ctrl: ctrl}
	mock.recorder = &MockInboundEmailProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInboundEmailProcessor) EXPECT() *MockInboundEmailProcessorMockRecorder {
	return m.recorder
}

// ProcessRawEmail mocks base method.
func (m *MockInboundEmailProcessor) ProcessRawEmail(ctx context.Context, bucket, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessRawEmail", ctx, bucket, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessRawEmail indicates an expected call of ProcessRawEmail.
func (mr *MockInboundEmailProcessorMockRecorder) ProcessRawEmail(ctx, bucket, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessRawEmail", reflect.TypeOf((*MockInboundEmailProcessor)(nil).ProcessRawEmail), ctx, bucket, key)
}
