// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/worker (interfaces: RiverClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_river_client.go -package=mocks . RiverClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	river "github.com/riverqueue/river"
	rivertype "github.com/riverqueue/river/rivertype"
	gomock "go.uber.org/mock/gomock"
)

// MockRiverClient is a mock of RiverClient interface.
type MockRiverClient struct {
	ctrl     *gomock.Controller
	recorder *MockRiverClientMockRecorder
	isgomock struct{}
}

// MockRiverClientMockRecorder is the mock recorder for MockRiverClient.
type MockRiverClientMockRecorder struct {
	mock *MockRiverClient
}

// NewMockRiverClient creates a new mock instance.
func NewMockRiverClient(ctrl *gomock.Controller) *MockRiverClient {
	mock := &MockRiverClient{ctrl: ctrl}
	mock.recorder = &MockRiverClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRiverClient) EXPECT() *MockRiverClientMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockRiverClient) Insert(ctx context.Context, args river.JobArgs, opts *river.InsertOpts) (*rivertype.JobInsertResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, args, opts)
	ret0, _ := ret[0].(*rivertype.JobInsertResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockRiverClientMockRecorder) Insert(ctx, args, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockRiverClient)(nil).Insert), ctx, args, opts)
}
