// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/transport/connect/interceptor (interfaces: APIKeyValidator,RateLimiterInterface,CreditCacheInterface,PolarClientInterface,UserRepositoryInterface,UserLookup,UserRoleLookup)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_interceptor.go -package=mocks github.com/emailapi/api/internal/transport/connect/interceptor APIKeyValidator,RateLimiterInterface,CreditCacheInterface,PolarClientInterface,UserRepositoryInterface,UserLookup,UserRoleLookup
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/emailapi/api/internal/domain"
	polar "github.com/emailapi/api/internal/external/polar"
	redis "github.com/emailapi/api/internal/repository/redis"
	gomock "go.uber.org/mock/gomock"
)

// MockAPIKeyValidator is a mock of APIKeyValidator interface.
type MockAPIKeyValidator struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyValidatorMockRecorder
	isgomock struct{}
}

// MockAPIKeyValidatorMockRecorder is the mock recorder for MockAPIKeyValidator.
type MockAPIKeyValidatorMockRecorder struct {
	mock *MockAPIKeyValidator
}

// NewMockAPIKeyValidator creates a new mock instance.
func NewMockAPIKeyValidator(ctrl *gomock.Controller) *MockAPIKeyValidator {
	mock := &MockAPIKeyValidator{ctrl: ctrl}
	mock.recorder = &MockAPIKeyValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyValidator) EXPECT() *MockAPIKeyValidatorMockRecorder {
	return m.recorder
}

// ValidateAndGetUser mocks base method.
func (m *MockAPIKeyValidator) ValidateAndGetUser(ctx context.Context, rawKey string) (*domain.User, *domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndGetUser", ctx, rawKey)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(*domain.APIKey)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateAndGetUser indicates an expected call of ValidateAndGetUser.
func (mr *MockAPIKeyValidatorMockRecorder) ValidateAndGetUser(ctx, rawKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndGetUser", reflect.TypeOf((*MockAPIKeyValidator)(nil).ValidateAndGetUser), ctx, rawKey)
}

// MockRateLimiterInterface is a mock of RateLimiterInterface interface.
type MockRateLimiterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterInterfaceMockRecorder
	isgomock struct{}
}

// MockRateLimiterInterfaceMockRecorder is the mock recorder for MockRateLimiterInterface.
type MockRateLimiterInterfaceMockRecorder struct {
	mock *MockRateLimiterInterface
}

// NewMockRateLimiterInterface creates a new mock instance.
func NewMockRateLimiterInterface(ctrl *gomock.Controller) *MockRateLimiterInterface {
	mock := &MockRateLimiterInterface{ctrl: ctrl}
	mock.recorder = &MockRateLimiterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiterInterface) EXPECT() *MockRateLimiterInterfaceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockRateLimiterInterface) Check(ctx context.Context, key string, limit int, window time.Duration) (*redis.RateLimitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, key, limit, window)
	ret0, _ := ret[0].(*redis.RateLimitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockRateLimiterInterfaceMockRecorder) Check(ctx, key, limit, window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockRateLimiterInterface)(nil).Check), ctx, key, limit, window)
}

// DecrementStreams mocks base method.
func (m *MockRateLimiterInterface) DecrementStreams(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementStreams", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementStreams indicates an expected call of DecrementStreams.
func (mr *MockRateLimiterInterfaceMockRecorder) DecrementStreams(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementStreams", reflect.TypeOf((*MockRateLimiterInterface)(nil).DecrementStreams), ctx, userID)
}

// IncrementStreams mocks base method.
func (m *MockRateLimiterInterface) IncrementStreams(ctx context.Context, userID string, maxStreams int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementStreams", ctx, userID, maxStreams)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementStreams indicates an expected call of IncrementStreams.
func (mr *MockRateLimiterInterfaceMockRecorder) IncrementStreams(ctx, userID, maxStreams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementStreams", reflect.TypeOf((*MockRateLimiterInterface)(nil).IncrementStreams), ctx, userID, maxStreams)
}

// MockCreditCacheInterface is a mock of CreditCacheInterface interface.
type MockCreditCacheInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCreditCacheInterfaceMockRecorder
	isgomock struct{}
}

// MockCreditCacheInterfaceMockRecorder is the mock recorder for MockCreditCacheInterface.
type MockCreditCacheInterfaceMockRecorder struct {
	mock *MockCreditCacheInterface
}

// NewMockCreditCacheInterface creates a new mock instance.
func NewMockCreditCacheInterface(ctrl *gomock.Controller) *MockCreditCacheInterface {
	mock := &MockCreditCacheInterface{ctrl: ctrl}
	mock.recorder = &MockCreditCacheInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreditCacheInterface) EXPECT() *MockCreditCacheInterfaceMockRecorder {
	return m.recorder
}

// GetConsumed mocks base method.
func (m *MockCreditCacheInterface) GetConsumed(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsumed", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsumed indicates an expected call of GetConsumed.
func (mr *MockCreditCacheInterfaceMockRecorder) GetConsumed(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsumed", reflect.TypeOf((*MockCreditCacheInterface)(nil).GetConsumed), ctx, userID)
}

// GetDailyUsage mocks base method.
func (m *MockCreditCacheInterface) GetDailyUsage(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyUsage", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyUsage indicates an expected call of GetDailyUsage.
func (mr *MockCreditCacheInterfaceMockRecorder) GetDailyUsage(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyUsage", reflect.TypeOf((*MockCreditCacheInterface)(nil).GetDailyUsage), ctx, userID)
}

// GetState mocks base method.
func (m *MockCreditCacheInterface) GetState(ctx context.Context, userID string) (*redis.CachedCustomerState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState", ctx, userID)
	ret0, _ := ret[0].(*redis.CachedCustomerState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetState indicates an expected call of GetState.
func (mr *MockCreditCacheInterfaceMockRecorder) GetState(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockCreditCacheInterface)(nil).GetState), ctx, userID)
}

// IncrConsumed mocks base method.
func (m *MockCreditCacheInterface) IncrConsumed(ctx context.Context, userID string, count int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrConsumed", ctx, userID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrConsumed indicates an expected call of IncrConsumed.
func (mr *MockCreditCacheInterfaceMockRecorder) IncrConsumed(ctx, userID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrConsumed", reflect.TypeOf((*MockCreditCacheInterface)(nil).IncrConsumed), ctx, userID, count)
}

// IncrDailyUsage mocks base method.
func (m *MockCreditCacheInterface) IncrDailyUsage(ctx context.Context, userID string, count int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrDailyUsage", ctx, userID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrDailyUsage indicates an expected call of IncrDailyUsage.
func (mr *MockCreditCacheInterfaceMockRecorder) IncrDailyUsage(ctx, userID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrDailyUsage", reflect.TypeOf((*MockCreditCacheInterface)(nil).IncrDailyUsage), ctx, userID, count)
}

// Invalidate mocks base method.
func (m *MockCreditCacheInterface) Invalidate(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockCreditCacheInterfaceMockRecorder) Invalidate(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockCreditCacheInterface)(nil).Invalidate), ctx, userID)
}

// SetStateAndResetConsumed mocks base method.
func (m *MockCreditCacheInterface) SetStateAndResetConsumed(ctx context.Context, userID string, state *redis.CachedCustomerState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStateAndResetConsumed", ctx, userID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStateAndResetConsumed indicates an expected call of SetStateAndResetConsumed.
func (mr *MockCreditCacheInterfaceMockRecorder) SetStateAndResetConsumed(ctx, userID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStateAndResetConsumed", reflect.TypeOf((*MockCreditCacheInterface)(nil).SetStateAndResetConsumed), ctx, userID, state)
}

// MockPolarClientInterface is a mock of PolarClientInterface interface.
type MockPolarClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPolarClientInterfaceMockRecorder
	isgomock struct{}
}

// MockPolarClientInterfaceMockRecorder is the mock recorder for MockPolarClientInterface.
type MockPolarClientInterfaceMockRecorder struct {
	mock *MockPolarClientInterface
}

// NewMockPolarClientInterface creates a new mock instance.
func NewMockPolarClientInterface(ctrl *gomock.Controller) *MockPolarClientInterface {
	mock := &MockPolarClientInterface{ctrl: ctrl}
	mock.recorder = &MockPolarClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolarClientInterface) EXPECT() *MockPolarClientInterfaceMockRecorder {
	return m.recorder
}

// CreateCheckoutSession mocks base method.
func (m *MockPolarClientInterface) CreateCheckoutSession(ctx context.Context, params polar.CheckoutParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCheckoutSession", ctx, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCheckoutSession indicates an expected call of CreateCheckoutSession.
func (mr *MockPolarClientInterfaceMockRecorder) CreateCheckoutSession(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheckoutSession", reflect.TypeOf((*MockPolarClientInterface)(nil).CreateCheckoutSession), ctx, params)
}

// CreateCustomer mocks base method.
func (m *MockPolarClientInterface) CreateCustomer(ctx context.Context, userID, email, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", ctx, userID, email, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockPolarClientInterfaceMockRecorder) CreateCustomer(ctx, userID, email, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockPolarClientInterface)(nil).CreateCustomer), ctx, userID, email, name)
}

// CreateCustomerPortal mocks base method.
func (m *MockPolarClientInterface) CreateCustomerPortal(ctx context.Context, customerID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomerPortal", ctx, customerID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomerPortal indicates an expected call of CreateCustomerPortal.
func (mr *MockPolarClientInterfaceMockRecorder) CreateCustomerPortal(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomerPortal", reflect.TypeOf((*MockPolarClientInterface)(nil).CreateCustomerPortal), ctx, customerID)
}

// CreateFreeSubscription mocks base method.
func (m *MockPolarClientInterface) CreateFreeSubscription(ctx context.Context, customerID, freeProductID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFreeSubscription", ctx, customerID, freeProductID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFreeSubscription indicates an expected call of CreateFreeSubscription.
func (mr *MockPolarClientInterfaceMockRecorder) CreateFreeSubscription(ctx, customerID, freeProductID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFreeSubscription", reflect.TypeOf((*MockPolarClientInterface)(nil).CreateFreeSubscription), ctx, customerID, freeProductID)
}

// GetActiveSubscriptionByExternalID mocks base method.
func (m *MockPolarClientInterface) GetActiveSubscriptionByExternalID(ctx context.Context, userID string) (*polar.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSubscriptionByExternalID", ctx, userID)
	ret0, _ := ret[0].(*polar.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveSubscriptionByExternalID indicates an expected call of GetActiveSubscriptionByExternalID.
func (mr *MockPolarClientInterfaceMockRecorder) GetActiveSubscriptionByExternalID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSubscriptionByExternalID", reflect.TypeOf((*MockPolarClientInterface)(nil).GetActiveSubscriptionByExternalID), ctx, userID)
}

// GetCustomerByExternalID mocks base method.
func (m *MockPolarClientInterface) GetCustomerByExternalID(ctx context.Context, userID string) (*polar.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerByExternalID", ctx, userID)
	ret0, _ := ret[0].(*polar.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByExternalID indicates an expected call of GetCustomerByExternalID.
func (mr *MockPolarClientInterfaceMockRecorder) GetCustomerByExternalID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByExternalID", reflect.TypeOf((*MockPolarClientInterface)(nil).GetCustomerByExternalID), ctx, userID)
}

// GetCustomerStateByExternalID mocks base method.
func (m *MockPolarClientInterface) GetCustomerStateByExternalID(ctx context.Context, userID string) (*polar.CustomerState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerStateByExternalID", ctx, userID)
	ret0, _ := ret[0].(*polar.CustomerState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerStateByExternalID indicates an expected call of GetCustomerStateByExternalID.
func (mr *MockPolarClientInterfaceMockRecorder) GetCustomerStateByExternalID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerStateByExternalID", reflect.TypeOf((*MockPolarClientInterface)(nil).GetCustomerStateByExternalID), ctx, userID)
}

// GetSubscription mocks base method.
func (m *MockPolarClientInterface) GetSubscription(ctx context.Context, customerID string) (*polar.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscription", ctx, customerID)
	ret0, _ := ret[0].(*polar.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockPolarClientInterfaceMockRecorder) GetSubscription(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscription", reflect.TypeOf((*MockPolarClientInterface)(nil).GetSubscription), ctx, customerID)
}

// IngestEmailEvent mocks base method.
func (m *MockPolarClientInterface) IngestEmailEvent(ctx context.Context, userID string, count int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestEmailEvent", ctx, userID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// IngestEmailEvent indicates an expected call of IngestEmailEvent.
func (mr *MockPolarClientInterfaceMockRecorder) IngestEmailEvent(ctx, userID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestEmailEvent", reflect.TypeOf((*MockPolarClientInterface)(nil).IngestEmailEvent), ctx, userID, count)
}

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface.
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface.
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance.
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserRepositoryInterface) GetByID(ctx context.Context, id string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByID), ctx, id)
}

// UpdatePolarCustomerID mocks base method.
func (m *MockUserRepositoryInterface) UpdatePolarCustomerID(ctx context.Context, id, polarCustomerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePolarCustomerID", ctx, id, polarCustomerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePolarCustomerID indicates an expected call of UpdatePolarCustomerID.
func (mr *MockUserRepositoryInterfaceMockRecorder) UpdatePolarCustomerID(ctx, id, polarCustomerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePolarCustomerID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UpdatePolarCustomerID), ctx, id, polarCustomerID)
}

// MockUserLookup is a mock of UserLookup interface.
type MockUserLookup struct {
	ctrl     *gomock.Controller
	recorder *MockUserLookupMockRecorder
	isgomock struct{}
}

// MockUserLookupMockRecorder is the mock recorder for MockUserLookup.
type MockUserLookupMockRecorder struct {
	mock *MockUserLookup
}

// NewMockUserLookup creates a new mock instance.
func NewMockUserLookup(ctrl *gomock.Controller) *MockUserLookup {
	mock := &MockUserLookup{ctrl: ctrl}
	mock.recorder = &MockUserLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserLookup) EXPECT() *MockUserLookupMockRecorder {
	return m.recorder
}

// GetByExternalID mocks base method.
func (m *MockUserLookup) GetByExternalID(ctx context.Context, externalID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByExternalID", ctx, externalID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByExternalID indicates an expected call of GetByExternalID.
func (mr *MockUserLookupMockRecorder) GetByExternalID(ctx, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByExternalID", reflect.TypeOf((*MockUserLookup)(nil).GetByExternalID), ctx, externalID)
}

// MockUserRoleLookup is a mock of UserRoleLookup interface.
type MockUserRoleLookup struct {
	ctrl     *gomock.Controller
	recorder *MockUserRoleLookupMockRecorder
	isgomock struct{}
}

// MockUserRoleLookupMockRecorder is the mock recorder for MockUserRoleLookup.
type MockUserRoleLookupMockRecorder struct {
	mock *MockUserRoleLookup
}

// NewMockUserRoleLookup creates a new mock instance.
func NewMockUserRoleLookup(ctrl *gomock.Controller) *MockUserRoleLookup {
	mock := &MockUserRoleLookup{ctrl: ctrl}
	mock.recorder = &MockUserRoleLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRoleLookup) EXPECT() *MockUserRoleLookupMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserRoleLookup) GetByID(ctx context.Context, id string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRoleLookupMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRoleLookup)(nil).GetByID), ctx, id)
}
