/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DomainsDomainIdRouteImport } from './routes/domains.$domainId'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsDomainIdRoute = DomainsDomainIdRouteImport.update({
  id: '/$domainId',
  path: '/$domainId',
  getParentRoute: () => DomainsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/domains': typeof DomainsRouteWithChildren
  '/user': typeof UserRoute
  '/domains/$domainId': typeof DomainsDomainIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/domains': typeof DomainsRouteWithChildren
  '/user': typeof UserRoute
  '/domains/$domainId': typeof DomainsDomainIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/domains': typeof DomainsRouteWithChildren
  '/user': typeof UserRoute
  '/domains/$domainId': typeof DomainsDomainIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api-keys' | '/domains' | '/user' | '/domains/$domainId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api-keys' | '/domains' | '/user' | '/domains/$domainId'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/domains'
    | '/user'
    | '/domains/$domainId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  DomainsRoute: typeof DomainsRouteWithChildren
  UserRoute: typeof UserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$domainId': {
      id: '/domains/$domainId'
      path: '/$domainId'
      fullPath: '/domains/$domainId'
      preLoaderRoute: typeof DomainsDomainIdRouteImport
      parentRoute: typeof DomainsRoute
    }
  }
}

interface DomainsRouteChildren {
  DomainsDomainIdRoute: typeof DomainsDomainIdRoute
}

const DomainsRouteChildren: DomainsRouteChildren = {
  DomainsDomainIdRoute: DomainsDomainIdRoute,
}

const DomainsRouteWithChildren =
  DomainsRoute._addFileChildren(DomainsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  DomainsRoute: DomainsRouteWithChildren,
  UserRoute: UserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
