/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as AuthedWebhooksRouteImport } from './routes/_authed/webhooks'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedApiKeysRouteImport } from './routes/_authed/api-keys'
import { Route as AuthedDomainsIndexRouteImport } from './routes/_authed/domains/index'
import { Route as AuthedDomainsDomainIdRouteImport } from './routes/_authed/domains/$domainId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWebhooksRoute = AuthedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApiKeysRoute = AuthedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDomainsIndexRoute = AuthedDomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDomainsDomainIdRoute = AuthedDomainsDomainIdRouteImport.update({
  id: '/domains/$domainId',
  path: '/domains/$domainId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api-keys': typeof AuthedApiKeysRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/webhooks': typeof AuthedWebhooksRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/domains/$domainId': typeof AuthedDomainsDomainIdRoute
  '/domains': typeof AuthedDomainsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api-keys': typeof AuthedApiKeysRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/webhooks': typeof AuthedWebhooksRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/domains/$domainId': typeof AuthedDomainsDomainIdRoute
  '/domains': typeof AuthedDomainsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/api-keys': typeof AuthedApiKeysRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/webhooks': typeof AuthedWebhooksRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/_authed/domains/$domainId': typeof AuthedDomainsDomainIdRoute
  '/_authed/domains/': typeof AuthedDomainsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api-keys'
    | '/dashboard'
    | '/webhooks'
    | '/api/search'
    | '/docs/$'
    | '/domains/$domainId'
    | '/domains'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api-keys'
    | '/dashboard'
    | '/webhooks'
    | '/api/search'
    | '/docs/$'
    | '/domains/$domainId'
    | '/domains'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/api-keys'
    | '/_authed/dashboard'
    | '/_authed/webhooks'
    | '/api/search'
    | '/docs/$'
    | '/_authed/domains/$domainId'
    | '/_authed/domains/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/webhooks': {
      id: '/_authed/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthedWebhooksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/api-keys': {
      id: '/_authed/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthedApiKeysRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/domains/': {
      id: '/_authed/domains/'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthedDomainsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/domains/$domainId': {
      id: '/_authed/domains/$domainId'
      path: '/domains/$domainId'
      fullPath: '/domains/$domainId'
      preLoaderRoute: typeof AuthedDomainsDomainIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedApiKeysRoute: typeof AuthedApiKeysRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedWebhooksRoute: typeof AuthedWebhooksRoute
  AuthedDomainsDomainIdRoute: typeof AuthedDomainsDomainIdRoute
  AuthedDomainsIndexRoute: typeof AuthedDomainsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedApiKeysRoute: AuthedApiKeysRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedWebhooksRoute: AuthedWebhooksRoute,
  AuthedDomainsDomainIdRoute: AuthedDomainsDomainIdRoute,
  AuthedDomainsIndexRoute: AuthedDomainsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
