/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminFlaggedRouteImport } from './routes/admin/flagged'
import { Route as AuthedWebhooksRouteImport } from './routes/_authed/webhooks'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedApiKeysRouteImport } from './routes/_authed/api-keys'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AuthedDomainsIndexRouteImport } from './routes/_authed/domains/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AuthedSettingsBillingRouteImport } from './routes/_authed/settings/billing'
import { Route as AuthedDomainsDomainIdRouteImport } from './routes/_authed/domains/$domainId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlaggedRoute = AdminFlaggedRouteImport.update({
  id: '/flagged',
  path: '/flagged',
  getParentRoute: () => AdminRoute,
} as any)
const AuthedWebhooksRoute = AuthedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApiKeysRoute = AuthedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthedRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthedDomainsIndexRoute = AuthedDomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => AuthedRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AuthedSettingsBillingRoute = AuthedSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDomainsDomainIdRoute = AuthedDomainsDomainIdRouteImport.update({
  id: '/domains/$domainId',
  path: '/domains/$domainId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api-keys': typeof AuthedApiKeysRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/webhooks': typeof AuthedWebhooksRoute
  '/admin/flagged': typeof AdminFlaggedRoute
  '/admin/': typeof AdminIndexRoute
  '/domains/$domainId': typeof AuthedDomainsDomainIdRoute
  '/settings/billing': typeof AuthedSettingsBillingRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/domains': typeof AuthedDomainsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api-keys': typeof AuthedApiKeysRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/webhooks': typeof AuthedWebhooksRoute
  '/admin/flagged': typeof AdminFlaggedRoute
  '/admin': typeof AdminIndexRoute
  '/domains/$domainId': typeof AuthedDomainsDomainIdRoute
  '/settings/billing': typeof AuthedSettingsBillingRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/domains': typeof AuthedDomainsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authed/api-keys': typeof AuthedApiKeysRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/webhooks': typeof AuthedWebhooksRoute
  '/admin/flagged': typeof AdminFlaggedRoute
  '/admin/': typeof AdminIndexRoute
  '/_authed/domains/$domainId': typeof AuthedDomainsDomainIdRoute
  '/_authed/settings/billing': typeof AuthedSettingsBillingRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/_authed/domains/': typeof AuthedDomainsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/api-keys'
    | '/dashboard'
    | '/webhooks'
    | '/admin/flagged'
    | '/admin/'
    | '/domains/$domainId'
    | '/settings/billing'
    | '/admin/users/$userId'
    | '/domains'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/api-keys'
    | '/dashboard'
    | '/webhooks'
    | '/admin/flagged'
    | '/admin'
    | '/domains/$domainId'
    | '/settings/billing'
    | '/admin/users/$userId'
    | '/domains'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/privacy'
    | '/terms'
    | '/_authed/api-keys'
    | '/_authed/dashboard'
    | '/_authed/webhooks'
    | '/admin/flagged'
    | '/admin/'
    | '/_authed/domains/$domainId'
    | '/_authed/settings/billing'
    | '/admin/users/$userId'
    | '/_authed/domains/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flagged': {
      id: '/admin/flagged'
      path: '/flagged'
      fullPath: '/admin/flagged'
      preLoaderRoute: typeof AdminFlaggedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authed/webhooks': {
      id: '/_authed/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthedWebhooksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/api-keys': {
      id: '/_authed/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthedApiKeysRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authed/domains/': {
      id: '/_authed/domains/'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthedDomainsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authed/settings/billing': {
      id: '/_authed/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthedSettingsBillingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/domains/$domainId': {
      id: '/_authed/domains/$domainId'
      path: '/domains/$domainId'
      fullPath: '/domains/$domainId'
      preLoaderRoute: typeof AuthedDomainsDomainIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedApiKeysRoute: typeof AuthedApiKeysRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedWebhooksRoute: typeof AuthedWebhooksRoute
  AuthedDomainsDomainIdRoute: typeof AuthedDomainsDomainIdRoute
  AuthedSettingsBillingRoute: typeof AuthedSettingsBillingRoute
  AuthedDomainsIndexRoute: typeof AuthedDomainsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedApiKeysRoute: AuthedApiKeysRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedWebhooksRoute: AuthedWebhooksRoute,
  AuthedDomainsDomainIdRoute: AuthedDomainsDomainIdRoute,
  AuthedSettingsBillingRoute: AuthedSettingsBillingRoute,
  AuthedDomainsIndexRoute: AuthedDomainsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AdminRouteChildren {
  AdminFlaggedRoute: typeof AdminFlaggedRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFlaggedRoute: AdminFlaggedRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
