// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/validation (interfaces: DomainChecker,SuppressionChecker,MXCache,UserCache,BodyValidatorInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_validation.go -package=mocks github.com/emailapi/api/internal/validation DomainChecker,SuppressionChecker,MXCache,UserCache,BodyValidatorInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/emailapi/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDomainChecker is a mock of DomainChecker interface.
type MockDomainChecker struct {
	ctrl     *gomock.Controller
	recorder *MockDomainCheckerMockRecorder
	isgomock struct{}
}

// MockDomainCheckerMockRecorder is the mock recorder for MockDomainChecker.
type MockDomainCheckerMockRecorder struct {
	mock *MockDomainChecker
}

// NewMockDomainChecker creates a new mock instance.
func NewMockDomainChecker(ctrl *gomock.Controller) *MockDomainChecker {
	mock := &MockDomainChecker{ctrl: ctrl}
	mock.recorder = &MockDomainCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainChecker) EXPECT() *MockDomainCheckerMockRecorder {
	return m.recorder
}

// GetVerifiedDomainForSending mocks base method.
func (m *MockDomainChecker) GetVerifiedDomainForSending(ctx context.Context, userID, domainName string) (*domain.SendingDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerifiedDomainForSending", ctx, userID, domainName)
	ret0, _ := ret[0].(*domain.SendingDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerifiedDomainForSending indicates an expected call of GetVerifiedDomainForSending.
func (mr *MockDomainCheckerMockRecorder) GetVerifiedDomainForSending(ctx, userID, domainName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerifiedDomainForSending", reflect.TypeOf((*MockDomainChecker)(nil).GetVerifiedDomainForSending), ctx, userID, domainName)
}

// MockSuppressionChecker is a mock of SuppressionChecker interface.
type MockSuppressionChecker struct {
	ctrl     *gomock.Controller
	recorder *MockSuppressionCheckerMockRecorder
	isgomock struct{}
}

// MockSuppressionCheckerMockRecorder is the mock recorder for MockSuppressionChecker.
type MockSuppressionCheckerMockRecorder struct {
	mock *MockSuppressionChecker
}

// NewMockSuppressionChecker creates a new mock instance.
func NewMockSuppressionChecker(ctrl *gomock.Controller) *MockSuppressionChecker {
	mock := &MockSuppressionChecker{ctrl: ctrl}
	mock.recorder = &MockSuppressionCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuppressionChecker) EXPECT() *MockSuppressionCheckerMockRecorder {
	return m.recorder
}

// CheckBatch mocks base method.
func (m *MockSuppressionChecker) CheckBatch(ctx context.Context, hashes []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBatch", ctx, hashes)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBatch indicates an expected call of CheckBatch.
func (mr *MockSuppressionCheckerMockRecorder) CheckBatch(ctx, hashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBatch", reflect.TypeOf((*MockSuppressionChecker)(nil).CheckBatch), ctx, hashes)
}

// MockMXCache is a mock of MXCache interface.
type MockMXCache struct {
	ctrl     *gomock.Controller
	recorder *MockMXCacheMockRecorder
	isgomock struct{}
}

// MockMXCacheMockRecorder is the mock recorder for MockMXCache.
type MockMXCacheMockRecorder struct {
	mock *MockMXCache
}

// NewMockMXCache creates a new mock instance.
func NewMockMXCache(ctrl *gomock.Controller) *MockMXCache {
	mock := &MockMXCache{ctrl: ctrl}
	mock.recorder = &MockMXCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMXCache) EXPECT() *MockMXCacheMockRecorder {
	return m.recorder
}

// HasMX mocks base method.
func (m *MockMXCache) HasMX(ctx context.Context, arg1 string) (*bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasMX", ctx, arg1)
	ret0, _ := ret[0].(*bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasMX indicates an expected call of HasMX.
func (mr *MockMXCacheMockRecorder) HasMX(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMX", reflect.TypeOf((*MockMXCache)(nil).HasMX), ctx, arg1)
}

// SetMX mocks base method.
func (m *MockMXCache) SetMX(ctx context.Context, arg1 string, hasMX bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMX", ctx, arg1, hasMX)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMX indicates an expected call of SetMX.
func (mr *MockMXCacheMockRecorder) SetMX(ctx, arg1, hasMX any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMX", reflect.TypeOf((*MockMXCache)(nil).SetMX), ctx, arg1, hasMX)
}

// MockUserCache is a mock of UserCache interface.
type MockUserCache struct {
	ctrl     *gomock.Controller
	recorder *MockUserCacheMockRecorder
	isgomock struct{}
}

// MockUserCacheMockRecorder is the mock recorder for MockUserCache.
type MockUserCacheMockRecorder struct {
	mock *MockUserCache
}

// NewMockUserCache creates a new mock instance.
func NewMockUserCache(ctrl *gomock.Controller) *MockUserCache {
	mock := &MockUserCache{ctrl: ctrl}
	mock.recorder = &MockUserCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCache) EXPECT() *MockUserCacheMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserCache) GetByID(ctx context.Context, id string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserCacheMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserCache)(nil).GetByID), ctx, id)
}

// MockBodyValidatorInterface is a mock of BodyValidatorInterface interface.
type MockBodyValidatorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBodyValidatorInterfaceMockRecorder
	isgomock struct{}
}

// MockBodyValidatorInterfaceMockRecorder is the mock recorder for MockBodyValidatorInterface.
type MockBodyValidatorInterfaceMockRecorder struct {
	mock *MockBodyValidatorInterface
}

// NewMockBodyValidatorInterface creates a new mock instance.
func NewMockBodyValidatorInterface(ctrl *gomock.Controller) *MockBodyValidatorInterface {
	mock := &MockBodyValidatorInterface{ctrl: ctrl}
	mock.recorder = &MockBodyValidatorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBodyValidatorInterface) EXPECT() *MockBodyValidatorInterfaceMockRecorder {
	return m.recorder
}

// ValidateURLs mocks base method.
func (m *MockBodyValidatorInterface) ValidateURLs(ctx context.Context, body, html string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateURLs", ctx, body, html)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateURLs indicates an expected call of ValidateURLs.
func (mr *MockBodyValidatorInterfaceMockRecorder) ValidateURLs(ctx, body, html any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateURLs", reflect.TypeOf((*MockBodyValidatorInterface)(nil).ValidateURLs), ctx, body, html)
}
