// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/validation (interfaces: ReputationChecker)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_reputation_checker.go -package=mocks github.com/emailapi/api/internal/validation ReputationChecker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReputationChecker is a mock of ReputationChecker interface.
type MockReputationChecker struct {
	ctrl     *gomock.Controller
	recorder *MockReputationCheckerMockRecorder
	isgomock struct{}
}

// MockReputationCheckerMockRecorder is the mock recorder for MockReputationChecker.
type MockReputationCheckerMockRecorder struct {
	mock *MockReputationChecker
}

// NewMockReputationChecker creates a new mock instance.
func NewMockReputationChecker(ctrl *gomock.Controller) *MockReputationChecker {
	mock := &MockReputationChecker{ctrl: ctrl}
	mock.recorder = &MockReputationCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReputationChecker) EXPECT() *MockReputationCheckerMockRecorder {
	return m.recorder
}

// CheckSendPermission mocks base method.
func (m *MockReputationChecker) CheckSendPermission(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSendPermission", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckSendPermission indicates an expected call of CheckSendPermission.
func (mr *MockReputationCheckerMockRecorder) CheckSendPermission(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSendPermission", reflect.TypeOf((*MockReputationChecker)(nil).CheckSendPermission), ctx, userID)
}

// GetEffectiveRateLimit mocks base method.
func (m *MockReputationChecker) GetEffectiveRateLimit(ctx context.Context, userID string, baseLimit int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEffectiveRateLimit", ctx, userID, baseLimit)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetEffectiveRateLimit indicates an expected call of GetEffectiveRateLimit.
func (mr *MockReputationCheckerMockRecorder) GetEffectiveRateLimit(ctx, userID, baseLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEffectiveRateLimit", reflect.TypeOf((*MockReputationChecker)(nil).GetEffectiveRateLimit), ctx, userID, baseLimit)
}
