// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/repository/suppression (interfaces: RepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_suppression.go -package=mocks github.com/emailapi/api/internal/repository/suppression RepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	suppression "github.com/emailapi/api/internal/repository/suppression"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRepositoryInterface) Add(ctx context.Context, entry *suppression.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockRepositoryInterfaceMockRecorder) Add(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRepositoryInterface)(nil).Add), ctx, entry)
}

// CheckBatch mocks base method.
func (m *MockRepositoryInterface) CheckBatch(ctx context.Context, hashes []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBatch", ctx, hashes)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBatch indicates an expected call of CheckBatch.
func (mr *MockRepositoryInterfaceMockRecorder) CheckBatch(ctx, hashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBatch", reflect.TypeOf((*MockRepositoryInterface)(nil).CheckBatch), ctx, hashes)
}

// Cleanup mocks base method.
func (m *MockRepositoryInterface) Cleanup(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockRepositoryInterfaceMockRecorder) Cleanup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockRepositoryInterface)(nil).Cleanup), ctx)
}

// Remove mocks base method.
func (m *MockRepositoryInterface) Remove(ctx context.Context, emailHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, emailHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRepositoryInterfaceMockRecorder) Remove(ctx, emailHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRepositoryInterface)(nil).Remove), ctx, emailHash)
}

// SyncFromPostgres mocks base method.
func (m *MockRepositoryInterface) SyncFromPostgres(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncFromPostgres", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncFromPostgres indicates an expected call of SyncFromPostgres.
func (mr *MockRepositoryInterfaceMockRecorder) SyncFromPostgres(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncFromPostgres", reflect.TypeOf((*MockRepositoryInterface)(nil).SyncFromPostgres), ctx)
}
