// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/webhook (interfaces: Sender)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_webhook.go -package=mocks github.com/emailapi/api/internal/webhook Sender
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1 "github.com/emailapi/api/gen/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// SendEmailBounced mocks base method.
func (m *MockSender) SendEmailBounced(ctx context.Context, userID string, event *v1.EmailBouncedEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEmailBounced", ctx, userID, event)
}

// SendEmailBounced indicates an expected call of SendEmailBounced.
func (mr *MockSenderMockRecorder) SendEmailBounced(ctx, userID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailBounced", reflect.TypeOf((*MockSender)(nil).SendEmailBounced), ctx, userID, event)
}

// SendEmailComplained mocks base method.
func (m *MockSender) SendEmailComplained(ctx context.Context, userID string, event *v1.EmailComplainedEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEmailComplained", ctx, userID, event)
}

// SendEmailComplained indicates an expected call of SendEmailComplained.
func (mr *MockSenderMockRecorder) SendEmailComplained(ctx, userID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailComplained", reflect.TypeOf((*MockSender)(nil).SendEmailComplained), ctx, userID, event)
}

// SendEmailDelayed mocks base method.
func (m *MockSender) SendEmailDelayed(ctx context.Context, userID string, event *v1.EmailDelayedEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEmailDelayed", ctx, userID, event)
}

// SendEmailDelayed indicates an expected call of SendEmailDelayed.
func (mr *MockSenderMockRecorder) SendEmailDelayed(ctx, userID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailDelayed", reflect.TypeOf((*MockSender)(nil).SendEmailDelayed), ctx, userID, event)
}

// SendEmailDelivered mocks base method.
func (m *MockSender) SendEmailDelivered(ctx context.Context, userID string, event *v1.EmailDeliveredEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEmailDelivered", ctx, userID, event)
}

// SendEmailDelivered indicates an expected call of SendEmailDelivered.
func (mr *MockSenderMockRecorder) SendEmailDelivered(ctx, userID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailDelivered", reflect.TypeOf((*MockSender)(nil).SendEmailDelivered), ctx, userID, event)
}

// SendEmailFailed mocks base method.
func (m *MockSender) SendEmailFailed(ctx context.Context, userID string, event *v1.EmailFailedEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEmailFailed", ctx, userID, event)
}

// SendEmailFailed indicates an expected call of SendEmailFailed.
func (mr *MockSenderMockRecorder) SendEmailFailed(ctx, userID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailFailed", reflect.TypeOf((*MockSender)(nil).SendEmailFailed), ctx, userID, event)
}

// SendEmailRejected mocks base method.
func (m *MockSender) SendEmailRejected(ctx context.Context, userID string, event *v1.EmailRejectedEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEmailRejected", ctx, userID, event)
}

// SendEmailRejected indicates an expected call of SendEmailRejected.
func (mr *MockSenderMockRecorder) SendEmailRejected(ctx, userID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailRejected", reflect.TypeOf((*MockSender)(nil).SendEmailRejected), ctx, userID, event)
}

// SendEmailReplied mocks base method.
func (m *MockSender) SendEmailReplied(ctx context.Context, userID string, event *v1.EmailRepliedEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEmailReplied", ctx, userID, event)
}

// SendEmailReplied indicates an expected call of SendEmailReplied.
func (mr *MockSenderMockRecorder) SendEmailReplied(ctx, userID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailReplied", reflect.TypeOf((*MockSender)(nil).SendEmailReplied), ctx, userID, event)
}

// SendEmailSent mocks base method.
func (m *MockSender) SendEmailSent(ctx context.Context, userID string, event *v1.EmailSentEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEmailSent", ctx, userID, event)
}

// SendEmailSent indicates an expected call of SendEmailSent.
func (mr *MockSenderMockRecorder) SendEmailSent(ctx, userID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailSent", reflect.TypeOf((*MockSender)(nil).SendEmailSent), ctx, userID, event)
}
