// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/repository/postgres (interfaces: UserRepository,APIKeyRepository,DomainRepository,EmailRepository,ReputationRepository,UnsubscribeRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_postgres.go -package=mocks github.com/emailapi/api/internal/repository/postgres UserRepository,APIKeyRepository,DomainRepository,EmailRepository,ReputationRepository,UnsubscribeRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/emailapi/api/internal/domain"
	postgres "github.com/emailapi/api/internal/repository/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockUserRepository) Count(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockUserRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockUserRepository)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByExternalID mocks base method.
func (m *MockUserRepository) GetByExternalID(ctx context.Context, externalID string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByExternalID", ctx, externalID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByExternalID indicates an expected call of GetByExternalID.
func (mr *MockUserRepositoryMockRecorder) GetByExternalID(ctx, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByExternalID", reflect.TypeOf((*MockUserRepository)(nil).GetByExternalID), ctx, externalID)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// GetWithReputation mocks base method.
func (m *MockUserRepository) GetWithReputation(ctx context.Context, userID string) (*domain.UserWithReputation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithReputation", ctx, userID)
	ret0, _ := ret[0].(*domain.UserWithReputation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithReputation indicates an expected call of GetWithReputation.
func (mr *MockUserRepositoryMockRecorder) GetWithReputation(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithReputation", reflect.TypeOf((*MockUserRepository)(nil).GetWithReputation), ctx, userID)
}

// List mocks base method.
func (m *MockUserRepository) List(ctx context.Context, limit, offset int) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserRepositoryMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepository)(nil).List), ctx, limit, offset)
}

// ListWithReputation mocks base method.
func (m *MockUserRepository) ListWithReputation(ctx context.Context, limit, offset int) ([]*domain.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithReputation", ctx, limit, offset)
	ret0, _ := ret[0].([]*domain.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithReputation indicates an expected call of ListWithReputation.
func (mr *MockUserRepositoryMockRecorder) ListWithReputation(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithReputation", reflect.TypeOf((*MockUserRepository)(nil).ListWithReputation), ctx, limit, offset)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, user)
}

// MockAPIKeyRepository is a mock of APIKeyRepository interface.
type MockAPIKeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyRepositoryMockRecorder
	isgomock struct{}
}

// MockAPIKeyRepositoryMockRecorder is the mock recorder for MockAPIKeyRepository.
type MockAPIKeyRepositoryMockRecorder struct {
	mock *MockAPIKeyRepository
}

// NewMockAPIKeyRepository creates a new mock instance.
func NewMockAPIKeyRepository(ctrl *gomock.Controller) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{ctrl: ctrl}
	mock.recorder = &MockAPIKeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepositoryMockRecorder {
	return m.recorder
}

// CountActiveByUserID mocks base method.
func (m *MockAPIKeyRepository) CountActiveByUserID(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveByUserID indicates an expected call of CountActiveByUserID.
func (mr *MockAPIKeyRepositoryMockRecorder) CountActiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveByUserID", reflect.TypeOf((*MockAPIKeyRepository)(nil).CountActiveByUserID), ctx, userID)
}

// CountByUserID mocks base method.
func (m *MockAPIKeyRepository) CountByUserID(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockAPIKeyRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockAPIKeyRepository)(nil).CountByUserID), ctx, userID)
}

// Create mocks base method.
func (m *MockAPIKeyRepository) Create(ctx context.Context, apiKey *domain.APIKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, apiKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAPIKeyRepositoryMockRecorder) Create(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAPIKeyRepository)(nil).Create), ctx, apiKey)
}

// Delete mocks base method.
func (m *MockAPIKeyRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAPIKeyRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAPIKeyRepository)(nil).Delete), ctx, id)
}

// GetByHash mocks base method.
func (m *MockAPIKeyRepository) GetByHash(ctx context.Context, keyHash string) (*domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", ctx, keyHash)
	ret0, _ := ret[0].(*domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockAPIKeyRepositoryMockRecorder) GetByHash(ctx, keyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockAPIKeyRepository)(nil).GetByHash), ctx, keyHash)
}

// GetByID mocks base method.
func (m *MockAPIKeyRepository) GetByID(ctx context.Context, id string) (*domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAPIKeyRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAPIKeyRepository)(nil).GetByID), ctx, id)
}

// GetByPrefix mocks base method.
func (m *MockAPIKeyRepository) GetByPrefix(ctx context.Context, keyPrefix string) (*domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPrefix", ctx, keyPrefix)
	ret0, _ := ret[0].(*domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPrefix indicates an expected call of GetByPrefix.
func (mr *MockAPIKeyRepositoryMockRecorder) GetByPrefix(ctx, keyPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPrefix", reflect.TypeOf((*MockAPIKeyRepository)(nil).GetByPrefix), ctx, keyPrefix)
}

// ListByUserID mocks base method.
func (m *MockAPIKeyRepository) ListByUserID(ctx context.Context, userID string, limit, offset int) ([]*domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockAPIKeyRepositoryMockRecorder) ListByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockAPIKeyRepository)(nil).ListByUserID), ctx, userID, limit, offset)
}

// Revoke mocks base method.
func (m *MockAPIKeyRepository) Revoke(ctx context.Context, id string) (*domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id)
	ret0, _ := ret[0].(*domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MockAPIKeyRepositoryMockRecorder) Revoke(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockAPIKeyRepository)(nil).Revoke), ctx, id)
}

// Update mocks base method.
func (m *MockAPIKeyRepository) Update(ctx context.Context, apiKey *domain.APIKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, apiKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAPIKeyRepositoryMockRecorder) Update(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAPIKeyRepository)(nil).Update), ctx, apiKey)
}

// UpdateLastUsed mocks base method.
func (m *MockAPIKeyRepository) UpdateLastUsed(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastUsed indicates an expected call of UpdateLastUsed.
func (mr *MockAPIKeyRepositoryMockRecorder) UpdateLastUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUsed", reflect.TypeOf((*MockAPIKeyRepository)(nil).UpdateLastUsed), ctx, id)
}

// MockDomainRepository is a mock of DomainRepository interface.
type MockDomainRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDomainRepositoryMockRecorder
	isgomock struct{}
}

// MockDomainRepositoryMockRecorder is the mock recorder for MockDomainRepository.
type MockDomainRepositoryMockRecorder struct {
	mock *MockDomainRepository
}

// NewMockDomainRepository creates a new mock instance.
func NewMockDomainRepository(ctrl *gomock.Controller) *MockDomainRepository {
	mock := &MockDomainRepository{ctrl: ctrl}
	mock.recorder = &MockDomainRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainRepository) EXPECT() *MockDomainRepositoryMockRecorder {
	return m.recorder
}

// CountByUserID mocks base method.
func (m *MockDomainRepository) CountByUserID(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockDomainRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockDomainRepository)(nil).CountByUserID), ctx, userID)
}

// Create mocks base method.
func (m *MockDomainRepository) Create(ctx context.Context, d *domain.SendingDomain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDomainRepositoryMockRecorder) Create(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDomainRepository)(nil).Create), ctx, d)
}

// Delete mocks base method.
func (m *MockDomainRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDomainRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDomainRepository)(nil).Delete), ctx, id)
}

// GetByDomainName mocks base method.
func (m *MockDomainRepository) GetByDomainName(ctx context.Context, userID, domainName string) (*domain.SendingDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDomainName", ctx, userID, domainName)
	ret0, _ := ret[0].(*domain.SendingDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDomainName indicates an expected call of GetByDomainName.
func (mr *MockDomainRepositoryMockRecorder) GetByDomainName(ctx, userID, domainName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDomainName", reflect.TypeOf((*MockDomainRepository)(nil).GetByDomainName), ctx, userID, domainName)
}

// GetByID mocks base method.
func (m *MockDomainRepository) GetByID(ctx context.Context, id string) (*domain.SendingDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.SendingDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDomainRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDomainRepository)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockDomainRepository) GetByUserID(ctx context.Context, userID string, limit, offset int) ([]*domain.SendingDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*domain.SendingDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockDomainRepositoryMockRecorder) GetByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockDomainRepository)(nil).GetByUserID), ctx, userID, limit, offset)
}

// Update mocks base method.
func (m *MockDomainRepository) Update(ctx context.Context, d *domain.SendingDomain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDomainRepositoryMockRecorder) Update(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDomainRepository)(nil).Update), ctx, d)
}

// MockEmailRepository is a mock of EmailRepository interface.
type MockEmailRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailRepositoryMockRecorder is the mock recorder for MockEmailRepository.
type MockEmailRepositoryMockRecorder struct {
	mock *MockEmailRepository
}

// NewMockEmailRepository creates a new mock instance.
func NewMockEmailRepository(ctrl *gomock.Controller) *MockEmailRepository {
	mock := &MockEmailRepository{ctrl: ctrl}
	mock.recorder = &MockEmailRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailRepository) EXPECT() *MockEmailRepositoryMockRecorder {
	return m.recorder
}

// AddEmail mocks base method.
func (m *MockEmailRepository) AddEmail(ctx context.Context, email *domain.Email, eventType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEmail", ctx, email, eventType)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEmail indicates an expected call of AddEmail.
func (mr *MockEmailRepositoryMockRecorder) AddEmail(ctx, email, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEmail", reflect.TypeOf((*MockEmailRepository)(nil).AddEmail), ctx, email, eventType)
}

// MockReputationRepository is a mock of ReputationRepository interface.
type MockReputationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReputationRepositoryMockRecorder
	isgomock struct{}
}

// MockReputationRepositoryMockRecorder is the mock recorder for MockReputationRepository.
type MockReputationRepositoryMockRecorder struct {
	mock *MockReputationRepository
}

// NewMockReputationRepository creates a new mock instance.
func NewMockReputationRepository(ctrl *gomock.Controller) *MockReputationRepository {
	mock := &MockReputationRepository{ctrl: ctrl}
	mock.recorder = &MockReputationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReputationRepository) EXPECT() *MockReputationRepositoryMockRecorder {
	return m.recorder
}

// CountIncidents mocks base method.
func (m *MockReputationRepository) CountIncidents(ctx context.Context, userID string) (*domain.IncidentStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountIncidents", ctx, userID)
	ret0, _ := ret[0].(*domain.IncidentStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountIncidents indicates an expected call of CountIncidents.
func (mr *MockReputationRepositoryMockRecorder) CountIncidents(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountIncidents", reflect.TypeOf((*MockReputationRepository)(nil).CountIncidents), ctx, userID)
}

// EnsureExists mocks base method.
func (m *MockReputationRepository) EnsureExists(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureExists", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureExists indicates an expected call of EnsureExists.
func (mr *MockReputationRepositoryMockRecorder) EnsureExists(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureExists", reflect.TypeOf((*MockReputationRepository)(nil).EnsureExists), ctx, userID)
}

// Get mocks base method.
func (m *MockReputationRepository) Get(ctx context.Context, userID string) (*domain.UserReputation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(*domain.UserReputation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockReputationRepositoryMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockReputationRepository)(nil).Get), ctx, userID)
}

// InsertIncident mocks base method.
func (m *MockReputationRepository) InsertIncident(ctx context.Context, incident *domain.ReputationIncident) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertIncident", ctx, incident)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertIncident indicates an expected call of InsertIncident.
func (mr *MockReputationRepositoryMockRecorder) InsertIncident(ctx, incident any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertIncident", reflect.TypeOf((*MockReputationRepository)(nil).InsertIncident), ctx, incident)
}

// ListFlagged mocks base method.
func (m *MockReputationRepository) ListFlagged(ctx context.Context, limit, offset int) ([]*domain.UserReputation, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFlagged", ctx, limit, offset)
	ret0, _ := ret[0].([]*domain.UserReputation)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFlagged indicates an expected call of ListFlagged.
func (mr *MockReputationRepositoryMockRecorder) ListFlagged(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFlagged", reflect.TypeOf((*MockReputationRepository)(nil).ListFlagged), ctx, limit, offset)
}

// ListIncidents mocks base method.
func (m *MockReputationRepository) ListIncidents(ctx context.Context, userID string, limit, offset int) ([]*domain.ReputationIncident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncidents", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*domain.ReputationIncident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncidents indicates an expected call of ListIncidents.
func (mr *MockReputationRepositoryMockRecorder) ListIncidents(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncidents", reflect.TypeOf((*MockReputationRepository)(nil).ListIncidents), ctx, userID, limit, offset)
}

// Suspend mocks base method.
func (m *MockReputationRepository) Suspend(ctx context.Context, userID, suspendedBy, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Suspend", ctx, userID, suspendedBy, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Suspend indicates an expected call of Suspend.
func (mr *MockReputationRepositoryMockRecorder) Suspend(ctx, userID, suspendedBy, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suspend", reflect.TypeOf((*MockReputationRepository)(nil).Suspend), ctx, userID, suspendedBy, reason)
}

// Unsuspend mocks base method.
func (m *MockReputationRepository) Unsuspend(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsuspend", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsuspend indicates an expected call of Unsuspend.
func (mr *MockReputationRepositoryMockRecorder) Unsuspend(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsuspend", reflect.TypeOf((*MockReputationRepository)(nil).Unsuspend), ctx, userID)
}

// UpdateStats mocks base method.
func (m *MockReputationRepository) UpdateStats(ctx context.Context, userID string, stats *domain.UserReputation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStats", ctx, userID, stats)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStats indicates an expected call of UpdateStats.
func (mr *MockReputationRepositoryMockRecorder) UpdateStats(ctx, userID, stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStats", reflect.TypeOf((*MockReputationRepository)(nil).UpdateStats), ctx, userID, stats)
}

// MockUnsubscribeRepository is a mock of UnsubscribeRepository interface.
type MockUnsubscribeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUnsubscribeRepositoryMockRecorder
	isgomock struct{}
}

// MockUnsubscribeRepositoryMockRecorder is the mock recorder for MockUnsubscribeRepository.
type MockUnsubscribeRepositoryMockRecorder struct {
	mock *MockUnsubscribeRepository
}

// NewMockUnsubscribeRepository creates a new mock instance.
func NewMockUnsubscribeRepository(ctrl *gomock.Controller) *MockUnsubscribeRepository {
	mock := &MockUnsubscribeRepository{ctrl: ctrl}
	mock.recorder = &MockUnsubscribeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsubscribeRepository) EXPECT() *MockUnsubscribeRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockUnsubscribeRepository) Add(ctx context.Context, entry *domain.UnsubscribeEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockUnsubscribeRepositoryMockRecorder) Add(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUnsubscribeRepository)(nil).Add), ctx, entry)
}

// CheckBatch mocks base method.
func (m *MockUnsubscribeRepository) CheckBatch(ctx context.Context, userID string, hashes []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBatch", ctx, userID, hashes)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBatch indicates an expected call of CheckBatch.
func (mr *MockUnsubscribeRepositoryMockRecorder) CheckBatch(ctx, userID, hashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBatch", reflect.TypeOf((*MockUnsubscribeRepository)(nil).CheckBatch), ctx, userID, hashes)
}

// CountByUserID mocks base method.
func (m *MockUnsubscribeRepository) CountByUserID(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockUnsubscribeRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockUnsubscribeRepository)(nil).CountByUserID), ctx, userID)
}

// Delete mocks base method.
func (m *MockUnsubscribeRepository) Delete(ctx context.Context, userID, emailHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, emailHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUnsubscribeRepositoryMockRecorder) Delete(ctx, userID, emailHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUnsubscribeRepository)(nil).Delete), ctx, userID, emailHash)
}

// GetByUserAndHash mocks base method.
func (m *MockUnsubscribeRepository) GetByUserAndHash(ctx context.Context, userID, emailHash string) (*domain.UnsubscribeEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAndHash", ctx, userID, emailHash)
	ret0, _ := ret[0].(*domain.UnsubscribeEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAndHash indicates an expected call of GetByUserAndHash.
func (mr *MockUnsubscribeRepositoryMockRecorder) GetByUserAndHash(ctx, userID, emailHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAndHash", reflect.TypeOf((*MockUnsubscribeRepository)(nil).GetByUserAndHash), ctx, userID, emailHash)
}

// ListAll mocks base method.
func (m *MockUnsubscribeRepository) ListAll(ctx context.Context) ([]postgres.UnsubscribeItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]postgres.UnsubscribeItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockUnsubscribeRepositoryMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockUnsubscribeRepository)(nil).ListAll), ctx)
}

// ListByUserID mocks base method.
func (m *MockUnsubscribeRepository) ListByUserID(ctx context.Context, userID string, limit, offset int) ([]*domain.UnsubscribeEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*domain.UnsubscribeEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockUnsubscribeRepositoryMockRecorder) ListByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockUnsubscribeRepository)(nil).ListByUserID), ctx, userID, limit, offset)
}
