// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/repository/redis (interfaces: UsageCacheInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_usage_cache.go -package=mocks github.com/emailapi/api/internal/repository/redis UsageCacheInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	redis "github.com/emailapi/api/internal/repository/redis"
	gomock "go.uber.org/mock/gomock"
)

// MockUsageCacheInterface is a mock of UsageCacheInterface interface.
type MockUsageCacheInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUsageCacheInterfaceMockRecorder
	isgomock struct{}
}

// MockUsageCacheInterfaceMockRecorder is the mock recorder for MockUsageCacheInterface.
type MockUsageCacheInterfaceMockRecorder struct {
	mock *MockUsageCacheInterface
}

// NewMockUsageCacheInterface creates a new mock instance.
func NewMockUsageCacheInterface(ctrl *gomock.Controller) *MockUsageCacheInterface {
	mock := &MockUsageCacheInterface{ctrl: ctrl}
	mock.recorder = &MockUsageCacheInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageCacheInterface) EXPECT() *MockUsageCacheInterfaceMockRecorder {
	return m.recorder
}

// GetDailyUsage mocks base method.
func (m *MockUsageCacheInterface) GetDailyUsage(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyUsage", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyUsage indicates an expected call of GetDailyUsage.
func (mr *MockUsageCacheInterfaceMockRecorder) GetDailyUsage(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyUsage", reflect.TypeOf((*MockUsageCacheInterface)(nil).GetDailyUsage), ctx, userID)
}

// GetMonthlyUsage mocks base method.
func (m *MockUsageCacheInterface) GetMonthlyUsage(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlyUsage", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlyUsage indicates an expected call of GetMonthlyUsage.
func (mr *MockUsageCacheInterfaceMockRecorder) GetMonthlyUsage(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlyUsage", reflect.TypeOf((*MockUsageCacheInterface)(nil).GetMonthlyUsage), ctx, userID)
}

// GetPlanState mocks base method.
func (m *MockUsageCacheInterface) GetPlanState(ctx context.Context, userID string) (*redis.PlanState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlanState", ctx, userID)
	ret0, _ := ret[0].(*redis.PlanState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlanState indicates an expected call of GetPlanState.
func (mr *MockUsageCacheInterfaceMockRecorder) GetPlanState(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlanState", reflect.TypeOf((*MockUsageCacheInterface)(nil).GetPlanState), ctx, userID)
}

// IncrementUsage mocks base method.
func (m *MockUsageCacheInterface) IncrementUsage(ctx context.Context, userID string, count int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUsage", ctx, userID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementUsage indicates an expected call of IncrementUsage.
func (mr *MockUsageCacheInterfaceMockRecorder) IncrementUsage(ctx, userID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUsage", reflect.TypeOf((*MockUsageCacheInterface)(nil).IncrementUsage), ctx, userID, count)
}

// InvalidatePlanState mocks base method.
func (m *MockUsageCacheInterface) InvalidatePlanState(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidatePlanState", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidatePlanState indicates an expected call of InvalidatePlanState.
func (mr *MockUsageCacheInterfaceMockRecorder) InvalidatePlanState(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidatePlanState", reflect.TypeOf((*MockUsageCacheInterface)(nil).InvalidatePlanState), ctx, userID)
}

// SetPlanState mocks base method.
func (m *MockUsageCacheInterface) SetPlanState(ctx context.Context, userID string, state *redis.PlanState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPlanState", ctx, userID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPlanState indicates an expected call of SetPlanState.
func (mr *MockUsageCacheInterfaceMockRecorder) SetPlanState(ctx, userID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPlanState", reflect.TypeOf((*MockUsageCacheInterface)(nil).SetPlanState), ctx, userID, state)
}
