// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/repository/redis (interfaces: CreditCacheInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_credit_cache.go -package=mocks github.com/emailapi/api/internal/repository/redis CreditCacheInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	redis "github.com/emailapi/api/internal/repository/redis"
	gomock "go.uber.org/mock/gomock"
)

// MockCreditCacheInterface is a mock of CreditCacheInterface interface.
type MockCreditCacheInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCreditCacheInterfaceMockRecorder
	isgomock struct{}
}

// MockCreditCacheInterfaceMockRecorder is the mock recorder for MockCreditCacheInterface.
type MockCreditCacheInterfaceMockRecorder struct {
	mock *MockCreditCacheInterface
}

// NewMockCreditCacheInterface creates a new mock instance.
func NewMockCreditCacheInterface(ctrl *gomock.Controller) *MockCreditCacheInterface {
	mock := &MockCreditCacheInterface{ctrl: ctrl}
	mock.recorder = &MockCreditCacheInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreditCacheInterface) EXPECT() *MockCreditCacheInterfaceMockRecorder {
	return m.recorder
}

// GetConsumed mocks base method.
func (m *MockCreditCacheInterface) GetConsumed(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsumed", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsumed indicates an expected call of GetConsumed.
func (mr *MockCreditCacheInterfaceMockRecorder) GetConsumed(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsumed", reflect.TypeOf((*MockCreditCacheInterface)(nil).GetConsumed), ctx, userID)
}

// GetDailyUsage mocks base method.
func (m *MockCreditCacheInterface) GetDailyUsage(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyUsage", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyUsage indicates an expected call of GetDailyUsage.
func (mr *MockCreditCacheInterfaceMockRecorder) GetDailyUsage(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyUsage", reflect.TypeOf((*MockCreditCacheInterface)(nil).GetDailyUsage), ctx, userID)
}

// GetState mocks base method.
func (m *MockCreditCacheInterface) GetState(ctx context.Context, userID string) (*redis.CachedCustomerState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState", ctx, userID)
	ret0, _ := ret[0].(*redis.CachedCustomerState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetState indicates an expected call of GetState.
func (mr *MockCreditCacheInterfaceMockRecorder) GetState(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockCreditCacheInterface)(nil).GetState), ctx, userID)
}

// GetSubscription mocks base method.
func (m *MockCreditCacheInterface) GetSubscription(ctx context.Context, userID string) (*redis.CachedSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscription", ctx, userID)
	ret0, _ := ret[0].(*redis.CachedSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockCreditCacheInterfaceMockRecorder) GetSubscription(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscription", reflect.TypeOf((*MockCreditCacheInterface)(nil).GetSubscription), ctx, userID)
}

// IncrConsumed mocks base method.
func (m *MockCreditCacheInterface) IncrConsumed(ctx context.Context, userID string, count int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrConsumed", ctx, userID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrConsumed indicates an expected call of IncrConsumed.
func (mr *MockCreditCacheInterfaceMockRecorder) IncrConsumed(ctx, userID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrConsumed", reflect.TypeOf((*MockCreditCacheInterface)(nil).IncrConsumed), ctx, userID, count)
}

// IncrDailyUsage mocks base method.
func (m *MockCreditCacheInterface) IncrDailyUsage(ctx context.Context, userID string, count int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrDailyUsage", ctx, userID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrDailyUsage indicates an expected call of IncrDailyUsage.
func (mr *MockCreditCacheInterfaceMockRecorder) IncrDailyUsage(ctx, userID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrDailyUsage", reflect.TypeOf((*MockCreditCacheInterface)(nil).IncrDailyUsage), ctx, userID, count)
}

// Invalidate mocks base method.
func (m *MockCreditCacheInterface) Invalidate(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockCreditCacheInterfaceMockRecorder) Invalidate(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockCreditCacheInterface)(nil).Invalidate), ctx, userID)
}

// SetStateAndResetConsumed mocks base method.
func (m *MockCreditCacheInterface) SetStateAndResetConsumed(ctx context.Context, userID string, state *redis.CachedCustomerState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStateAndResetConsumed", ctx, userID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStateAndResetConsumed indicates an expected call of SetStateAndResetConsumed.
func (mr *MockCreditCacheInterfaceMockRecorder) SetStateAndResetConsumed(ctx, userID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStateAndResetConsumed", reflect.TypeOf((*MockCreditCacheInterface)(nil).SetStateAndResetConsumed), ctx, userID, state)
}

// SetSubscription mocks base method.
func (m *MockCreditCacheInterface) SetSubscription(ctx context.Context, userID string, sub *redis.CachedSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSubscription", ctx, userID, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSubscription indicates an expected call of SetSubscription.
func (mr *MockCreditCacheInterfaceMockRecorder) SetSubscription(ctx, userID, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSubscription", reflect.TypeOf((*MockCreditCacheInterface)(nil).SetSubscription), ctx, userID, sub)
}
