// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/repository/redis (interfaces: DomainCacheInterface,APIKeyCacheInterface,UserCacheInterface,MXCacheInterface,ReputationCacheInterface,UnsubscribeCacheInterface,PendingAttachmentCacheInterface,WebRiskCacheInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_cache.go -package=mocks github.com/emailapi/api/internal/repository/redis DomainCacheInterface,APIKeyCacheInterface,UserCacheInterface,MXCacheInterface,ReputationCacheInterface,UnsubscribeCacheInterface,PendingAttachmentCacheInterface,WebRiskCacheInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/emailapi/api/internal/domain"
	redis "github.com/emailapi/api/internal/repository/redis"
	gomock "go.uber.org/mock/gomock"
)

// MockDomainCacheInterface is a mock of DomainCacheInterface interface.
type MockDomainCacheInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDomainCacheInterfaceMockRecorder
	isgomock struct{}
}

// MockDomainCacheInterfaceMockRecorder is the mock recorder for MockDomainCacheInterface.
type MockDomainCacheInterfaceMockRecorder struct {
	mock *MockDomainCacheInterface
}

// NewMockDomainCacheInterface creates a new mock instance.
func NewMockDomainCacheInterface(ctrl *gomock.Controller) *MockDomainCacheInterface {
	mock := &MockDomainCacheInterface{ctrl: ctrl}
	mock.recorder = &MockDomainCacheInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainCacheInterface) EXPECT() *MockDomainCacheInterfaceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockDomainCacheInterface) GetByID(ctx context.Context, id string) (*domain.SendingDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.SendingDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDomainCacheInterfaceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDomainCacheInterface)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockDomainCacheInterface) GetByUserID(ctx context.Context, userID string) ([]*domain.SendingDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.SendingDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockDomainCacheInterfaceMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockDomainCacheInterface)(nil).GetByUserID), ctx, userID)
}

// GetDetailsByID mocks base method.
func (m *MockDomainCacheInterface) GetDetailsByID(ctx context.Context, id string) (*domain.DomainWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetailsByID", ctx, id)
	ret0, _ := ret[0].(*domain.DomainWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetailsByID indicates an expected call of GetDetailsByID.
func (mr *MockDomainCacheInterfaceMockRecorder) GetDetailsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetailsByID", reflect.TypeOf((*MockDomainCacheInterface)(nil).GetDetailsByID), ctx, id)
}

// GetSendingStatus mocks base method.
func (m *MockDomainCacheInterface) GetSendingStatus(ctx context.Context, userID, domainName string) (*domain.SendingDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSendingStatus", ctx, userID, domainName)
	ret0, _ := ret[0].(*domain.SendingDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSendingStatus indicates an expected call of GetSendingStatus.
func (mr *MockDomainCacheInterfaceMockRecorder) GetSendingStatus(ctx, userID, domainName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSendingStatus", reflect.TypeOf((*MockDomainCacheInterface)(nil).GetSendingStatus), ctx, userID, domainName)
}

// InvalidateAll mocks base method.
func (m *MockDomainCacheInterface) InvalidateAll(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAll", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAll indicates an expected call of InvalidateAll.
func (mr *MockDomainCacheInterfaceMockRecorder) InvalidateAll(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAll", reflect.TypeOf((*MockDomainCacheInterface)(nil).InvalidateAll), ctx, id, userID)
}

// InvalidateByID mocks base method.
func (m *MockDomainCacheInterface) InvalidateByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateByID indicates an expected call of InvalidateByID.
func (mr *MockDomainCacheInterfaceMockRecorder) InvalidateByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateByID", reflect.TypeOf((*MockDomainCacheInterface)(nil).InvalidateByID), ctx, id)
}

// InvalidateByUserID mocks base method.
func (m *MockDomainCacheInterface) InvalidateByUserID(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateByUserID indicates an expected call of InvalidateByUserID.
func (mr *MockDomainCacheInterfaceMockRecorder) InvalidateByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateByUserID", reflect.TypeOf((*MockDomainCacheInterface)(nil).InvalidateByUserID), ctx, userID)
}

// InvalidateSendingStatus mocks base method.
func (m *MockDomainCacheInterface) InvalidateSendingStatus(ctx context.Context, userID, domainName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateSendingStatus", ctx, userID, domainName)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateSendingStatus indicates an expected call of InvalidateSendingStatus.
func (mr *MockDomainCacheInterfaceMockRecorder) InvalidateSendingStatus(ctx, userID, domainName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateSendingStatus", reflect.TypeOf((*MockDomainCacheInterface)(nil).InvalidateSendingStatus), ctx, userID, domainName)
}

// SetByID mocks base method.
func (m *MockDomainCacheInterface) SetByID(ctx context.Context, d *domain.SendingDomain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetByID", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetByID indicates an expected call of SetByID.
func (mr *MockDomainCacheInterfaceMockRecorder) SetByID(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetByID", reflect.TypeOf((*MockDomainCacheInterface)(nil).SetByID), ctx, d)
}

// SetByUserID mocks base method.
func (m *MockDomainCacheInterface) SetByUserID(ctx context.Context, userID string, domains []*domain.SendingDomain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetByUserID", ctx, userID, domains)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetByUserID indicates an expected call of SetByUserID.
func (mr *MockDomainCacheInterfaceMockRecorder) SetByUserID(ctx, userID, domains any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetByUserID", reflect.TypeOf((*MockDomainCacheInterface)(nil).SetByUserID), ctx, userID, domains)
}

// SetDetailsByID mocks base method.
func (m *MockDomainCacheInterface) SetDetailsByID(ctx context.Context, d *domain.DomainWithDetails) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDetailsByID", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDetailsByID indicates an expected call of SetDetailsByID.
func (mr *MockDomainCacheInterfaceMockRecorder) SetDetailsByID(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDetailsByID", reflect.TypeOf((*MockDomainCacheInterface)(nil).SetDetailsByID), ctx, d)
}

// SetSendingStatus mocks base method.
func (m *MockDomainCacheInterface) SetSendingStatus(ctx context.Context, d *domain.SendingDomain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSendingStatus", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSendingStatus indicates an expected call of SetSendingStatus.
func (mr *MockDomainCacheInterfaceMockRecorder) SetSendingStatus(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSendingStatus", reflect.TypeOf((*MockDomainCacheInterface)(nil).SetSendingStatus), ctx, d)
}

// MockAPIKeyCacheInterface is a mock of APIKeyCacheInterface interface.
type MockAPIKeyCacheInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyCacheInterfaceMockRecorder
	isgomock struct{}
}

// MockAPIKeyCacheInterfaceMockRecorder is the mock recorder for MockAPIKeyCacheInterface.
type MockAPIKeyCacheInterfaceMockRecorder struct {
	mock *MockAPIKeyCacheInterface
}

// NewMockAPIKeyCacheInterface creates a new mock instance.
func NewMockAPIKeyCacheInterface(ctrl *gomock.Controller) *MockAPIKeyCacheInterface {
	mock := &MockAPIKeyCacheInterface{ctrl: ctrl}
	mock.recorder = &MockAPIKeyCacheInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyCacheInterface) EXPECT() *MockAPIKeyCacheInterfaceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockAPIKeyCacheInterface) GetByID(ctx context.Context, id string) (*domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAPIKeyCacheInterfaceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAPIKeyCacheInterface)(nil).GetByID), ctx, id)
}

// GetByKeyHash mocks base method.
func (m *MockAPIKeyCacheInterface) GetByKeyHash(ctx context.Context, keyHash string) (*domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKeyHash", ctx, keyHash)
	ret0, _ := ret[0].(*domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKeyHash indicates an expected call of GetByKeyHash.
func (mr *MockAPIKeyCacheInterfaceMockRecorder) GetByKeyHash(ctx, keyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKeyHash", reflect.TypeOf((*MockAPIKeyCacheInterface)(nil).GetByKeyHash), ctx, keyHash)
}

// GetByPrefix mocks base method.
func (m *MockAPIKeyCacheInterface) GetByPrefix(ctx context.Context, prefix string) (*domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPrefix", ctx, prefix)
	ret0, _ := ret[0].(*domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPrefix indicates an expected call of GetByPrefix.
func (mr *MockAPIKeyCacheInterfaceMockRecorder) GetByPrefix(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPrefix", reflect.TypeOf((*MockAPIKeyCacheInterface)(nil).GetByPrefix), ctx, prefix)
}

// GetByUserID mocks base method.
func (m *MockAPIKeyCacheInterface) GetByUserID(ctx context.Context, userID string) ([]*domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockAPIKeyCacheInterfaceMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockAPIKeyCacheInterface)(nil).GetByUserID), ctx, userID)
}

// InvalidateAll mocks base method.
func (m *MockAPIKeyCacheInterface) InvalidateAll(ctx context.Context, id, prefix, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAll", ctx, id, prefix, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAll indicates an expected call of InvalidateAll.
func (mr *MockAPIKeyCacheInterfaceMockRecorder) InvalidateAll(ctx, id, prefix, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAll", reflect.TypeOf((*MockAPIKeyCacheInterface)(nil).InvalidateAll), ctx, id, prefix, userID)
}

// InvalidateByID mocks base method.
func (m *MockAPIKeyCacheInterface) InvalidateByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateByID indicates an expected call of InvalidateByID.
func (mr *MockAPIKeyCacheInterfaceMockRecorder) InvalidateByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateByID", reflect.TypeOf((*MockAPIKeyCacheInterface)(nil).InvalidateByID), ctx, id)
}

// InvalidateByKeyHash mocks base method.
func (m *MockAPIKeyCacheInterface) InvalidateByKeyHash(ctx context.Context, keyHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateByKeyHash", ctx, keyHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateByKeyHash indicates an expected call of InvalidateByKeyHash.
func (mr *MockAPIKeyCacheInterfaceMockRecorder) InvalidateByKeyHash(ctx, keyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateByKeyHash", reflect.TypeOf((*MockAPIKeyCacheInterface)(nil).InvalidateByKeyHash), ctx, keyHash)
}

// InvalidateByPrefix mocks base method.
func (m *MockAPIKeyCacheInterface) InvalidateByPrefix(ctx context.Context, prefix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateByPrefix", ctx, prefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateByPrefix indicates an expected call of InvalidateByPrefix.
func (mr *MockAPIKeyCacheInterfaceMockRecorder) InvalidateByPrefix(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateByPrefix", reflect.TypeOf((*MockAPIKeyCacheInterface)(nil).InvalidateByPrefix), ctx, prefix)
}

// InvalidateByUserID mocks base method.
func (m *MockAPIKeyCacheInterface) InvalidateByUserID(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateByUserID indicates an expected call of InvalidateByUserID.
func (mr *MockAPIKeyCacheInterfaceMockRecorder) InvalidateByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateByUserID", reflect.TypeOf((*MockAPIKeyCacheInterface)(nil).InvalidateByUserID), ctx, userID)
}

// SetByID mocks base method.
func (m *MockAPIKeyCacheInterface) SetByID(ctx context.Context, k *domain.APIKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetByID", ctx, k)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetByID indicates an expected call of SetByID.
func (mr *MockAPIKeyCacheInterfaceMockRecorder) SetByID(ctx, k any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetByID", reflect.TypeOf((*MockAPIKeyCacheInterface)(nil).SetByID), ctx, k)
}

// SetByKeyHash mocks base method.
func (m *MockAPIKeyCacheInterface) SetByKeyHash(ctx context.Context, keyHash string, k *domain.APIKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetByKeyHash", ctx, keyHash, k)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetByKeyHash indicates an expected call of SetByKeyHash.
func (mr *MockAPIKeyCacheInterfaceMockRecorder) SetByKeyHash(ctx, keyHash, k any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetByKeyHash", reflect.TypeOf((*MockAPIKeyCacheInterface)(nil).SetByKeyHash), ctx, keyHash, k)
}

// SetByPrefix mocks base method.
func (m *MockAPIKeyCacheInterface) SetByPrefix(ctx context.Context, k *domain.APIKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetByPrefix", ctx, k)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetByPrefix indicates an expected call of SetByPrefix.
func (mr *MockAPIKeyCacheInterfaceMockRecorder) SetByPrefix(ctx, k any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetByPrefix", reflect.TypeOf((*MockAPIKeyCacheInterface)(nil).SetByPrefix), ctx, k)
}

// SetByUserID mocks base method.
func (m *MockAPIKeyCacheInterface) SetByUserID(ctx context.Context, userID string, keys []*domain.APIKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetByUserID", ctx, userID, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetByUserID indicates an expected call of SetByUserID.
func (mr *MockAPIKeyCacheInterfaceMockRecorder) SetByUserID(ctx, userID, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetByUserID", reflect.TypeOf((*MockAPIKeyCacheInterface)(nil).SetByUserID), ctx, userID, keys)
}

// MockUserCacheInterface is a mock of UserCacheInterface interface.
type MockUserCacheInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserCacheInterfaceMockRecorder
	isgomock struct{}
}

// MockUserCacheInterfaceMockRecorder is the mock recorder for MockUserCacheInterface.
type MockUserCacheInterfaceMockRecorder struct {
	mock *MockUserCacheInterface
}

// NewMockUserCacheInterface creates a new mock instance.
func NewMockUserCacheInterface(ctrl *gomock.Controller) *MockUserCacheInterface {
	mock := &MockUserCacheInterface{ctrl: ctrl}
	mock.recorder = &MockUserCacheInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCacheInterface) EXPECT() *MockUserCacheInterfaceMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockUserCacheInterface) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserCacheInterfaceMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserCacheInterface)(nil).GetByEmail), ctx, email)
}

// GetByExternalID mocks base method.
func (m *MockUserCacheInterface) GetByExternalID(ctx context.Context, externalID string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByExternalID", ctx, externalID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByExternalID indicates an expected call of GetByExternalID.
func (mr *MockUserCacheInterfaceMockRecorder) GetByExternalID(ctx, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByExternalID", reflect.TypeOf((*MockUserCacheInterface)(nil).GetByExternalID), ctx, externalID)
}

// GetByID mocks base method.
func (m *MockUserCacheInterface) GetByID(ctx context.Context, id string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserCacheInterfaceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserCacheInterface)(nil).GetByID), ctx, id)
}

// InvalidateAll mocks base method.
func (m *MockUserCacheInterface) InvalidateAll(ctx context.Context, id, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAll", ctx, id, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAll indicates an expected call of InvalidateAll.
func (mr *MockUserCacheInterfaceMockRecorder) InvalidateAll(ctx, id, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAll", reflect.TypeOf((*MockUserCacheInterface)(nil).InvalidateAll), ctx, id, email)
}

// InvalidateByEmail mocks base method.
func (m *MockUserCacheInterface) InvalidateByEmail(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateByEmail", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateByEmail indicates an expected call of InvalidateByEmail.
func (mr *MockUserCacheInterfaceMockRecorder) InvalidateByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateByEmail", reflect.TypeOf((*MockUserCacheInterface)(nil).InvalidateByEmail), ctx, email)
}

// InvalidateByExternalID mocks base method.
func (m *MockUserCacheInterface) InvalidateByExternalID(ctx context.Context, externalID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateByExternalID", ctx, externalID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateByExternalID indicates an expected call of InvalidateByExternalID.
func (mr *MockUserCacheInterfaceMockRecorder) InvalidateByExternalID(ctx, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateByExternalID", reflect.TypeOf((*MockUserCacheInterface)(nil).InvalidateByExternalID), ctx, externalID)
}

// InvalidateByID mocks base method.
func (m *MockUserCacheInterface) InvalidateByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateByID indicates an expected call of InvalidateByID.
func (mr *MockUserCacheInterfaceMockRecorder) InvalidateByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateByID", reflect.TypeOf((*MockUserCacheInterface)(nil).InvalidateByID), ctx, id)
}

// SetByEmail mocks base method.
func (m *MockUserCacheInterface) SetByEmail(ctx context.Context, u *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetByEmail", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetByEmail indicates an expected call of SetByEmail.
func (mr *MockUserCacheInterfaceMockRecorder) SetByEmail(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetByEmail", reflect.TypeOf((*MockUserCacheInterface)(nil).SetByEmail), ctx, u)
}

// SetByExternalID mocks base method.
func (m *MockUserCacheInterface) SetByExternalID(ctx context.Context, u *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetByExternalID", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetByExternalID indicates an expected call of SetByExternalID.
func (mr *MockUserCacheInterfaceMockRecorder) SetByExternalID(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetByExternalID", reflect.TypeOf((*MockUserCacheInterface)(nil).SetByExternalID), ctx, u)
}

// SetByID mocks base method.
func (m *MockUserCacheInterface) SetByID(ctx context.Context, u *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetByID", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetByID indicates an expected call of SetByID.
func (mr *MockUserCacheInterfaceMockRecorder) SetByID(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetByID", reflect.TypeOf((*MockUserCacheInterface)(nil).SetByID), ctx, u)
}

// MockMXCacheInterface is a mock of MXCacheInterface interface.
type MockMXCacheInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMXCacheInterfaceMockRecorder
	isgomock struct{}
}

// MockMXCacheInterfaceMockRecorder is the mock recorder for MockMXCacheInterface.
type MockMXCacheInterfaceMockRecorder struct {
	mock *MockMXCacheInterface
}

// NewMockMXCacheInterface creates a new mock instance.
func NewMockMXCacheInterface(ctrl *gomock.Controller) *MockMXCacheInterface {
	mock := &MockMXCacheInterface{ctrl: ctrl}
	mock.recorder = &MockMXCacheInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMXCacheInterface) EXPECT() *MockMXCacheInterfaceMockRecorder {
	return m.recorder
}

// HasMX mocks base method.
func (m *MockMXCacheInterface) HasMX(ctx context.Context, arg1 string) (*bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasMX", ctx, arg1)
	ret0, _ := ret[0].(*bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasMX indicates an expected call of HasMX.
func (mr *MockMXCacheInterfaceMockRecorder) HasMX(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMX", reflect.TypeOf((*MockMXCacheInterface)(nil).HasMX), ctx, arg1)
}

// SetMX mocks base method.
func (m *MockMXCacheInterface) SetMX(ctx context.Context, arg1 string, hasMX bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMX", ctx, arg1, hasMX)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMX indicates an expected call of SetMX.
func (mr *MockMXCacheInterfaceMockRecorder) SetMX(ctx, arg1, hasMX any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMX", reflect.TypeOf((*MockMXCacheInterface)(nil).SetMX), ctx, arg1, hasMX)
}

// MockReputationCacheInterface is a mock of ReputationCacheInterface interface.
type MockReputationCacheInterface struct {
	ctrl     *gomock.Controller
	recorder *MockReputationCacheInterfaceMockRecorder
	isgomock struct{}
}

// MockReputationCacheInterfaceMockRecorder is the mock recorder for MockReputationCacheInterface.
type MockReputationCacheInterfaceMockRecorder struct {
	mock *MockReputationCacheInterface
}

// NewMockReputationCacheInterface creates a new mock instance.
func NewMockReputationCacheInterface(ctrl *gomock.Controller) *MockReputationCacheInterface {
	mock := &MockReputationCacheInterface{ctrl: ctrl}
	mock.recorder = &MockReputationCacheInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReputationCacheInterface) EXPECT() *MockReputationCacheInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockReputationCacheInterface) Delete(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReputationCacheInterfaceMockRecorder) Delete(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReputationCacheInterface)(nil).Delete), ctx, userID)
}

// Get mocks base method.
func (m *MockReputationCacheInterface) Get(ctx context.Context, userID string) (*redis.UserReputationStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(*redis.UserReputationStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockReputationCacheInterfaceMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockReputationCacheInterface)(nil).Get), ctx, userID)
}

// Set mocks base method.
func (m *MockReputationCacheInterface) Set(ctx context.Context, userID string, status *redis.UserReputationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, userID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockReputationCacheInterfaceMockRecorder) Set(ctx, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockReputationCacheInterface)(nil).Set), ctx, userID, status)
}

// SetHardSuspended mocks base method.
func (m *MockReputationCacheInterface) SetHardSuspended(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHardSuspended", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHardSuspended indicates an expected call of SetHardSuspended.
func (mr *MockReputationCacheInterfaceMockRecorder) SetHardSuspended(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHardSuspended", reflect.TypeOf((*MockReputationCacheInterface)(nil).SetHardSuspended), ctx, userID)
}

// SetSoftSuspended mocks base method.
func (m *MockReputationCacheInterface) SetSoftSuspended(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSoftSuspended", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSoftSuspended indicates an expected call of SetSoftSuspended.
func (mr *MockReputationCacheInterfaceMockRecorder) SetSoftSuspended(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSoftSuspended", reflect.TypeOf((*MockReputationCacheInterface)(nil).SetSoftSuspended), ctx, userID)
}

// SetSuspended mocks base method.
func (m *MockReputationCacheInterface) SetSuspended(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSuspended", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSuspended indicates an expected call of SetSuspended.
func (mr *MockReputationCacheInterfaceMockRecorder) SetSuspended(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSuspended", reflect.TypeOf((*MockReputationCacheInterface)(nil).SetSuspended), ctx, userID)
}

// MockUnsubscribeCacheInterface is a mock of UnsubscribeCacheInterface interface.
type MockUnsubscribeCacheInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUnsubscribeCacheInterfaceMockRecorder
	isgomock struct{}
}

// MockUnsubscribeCacheInterfaceMockRecorder is the mock recorder for MockUnsubscribeCacheInterface.
type MockUnsubscribeCacheInterfaceMockRecorder struct {
	mock *MockUnsubscribeCacheInterface
}

// NewMockUnsubscribeCacheInterface creates a new mock instance.
func NewMockUnsubscribeCacheInterface(ctrl *gomock.Controller) *MockUnsubscribeCacheInterface {
	mock := &MockUnsubscribeCacheInterface{ctrl: ctrl}
	mock.recorder = &MockUnsubscribeCacheInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsubscribeCacheInterface) EXPECT() *MockUnsubscribeCacheInterfaceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockUnsubscribeCacheInterface) Check(ctx context.Context, userID, emailHash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, userID, emailHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockUnsubscribeCacheInterfaceMockRecorder) Check(ctx, userID, emailHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockUnsubscribeCacheInterface)(nil).Check), ctx, userID, emailHash)
}

// CheckBatch mocks base method.
func (m *MockUnsubscribeCacheInterface) CheckBatch(ctx context.Context, userID string, hashes []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBatch", ctx, userID, hashes)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBatch indicates an expected call of CheckBatch.
func (mr *MockUnsubscribeCacheInterfaceMockRecorder) CheckBatch(ctx, userID, hashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBatch", reflect.TypeOf((*MockUnsubscribeCacheInterface)(nil).CheckBatch), ctx, userID, hashes)
}

// Delete mocks base method.
func (m *MockUnsubscribeCacheInterface) Delete(ctx context.Context, userID, emailHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, emailHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUnsubscribeCacheInterfaceMockRecorder) Delete(ctx, userID, emailHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUnsubscribeCacheInterface)(nil).Delete), ctx, userID, emailHash)
}

// Set mocks base method.
func (m *MockUnsubscribeCacheInterface) Set(ctx context.Context, userID, emailHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, userID, emailHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockUnsubscribeCacheInterfaceMockRecorder) Set(ctx, userID, emailHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockUnsubscribeCacheInterface)(nil).Set), ctx, userID, emailHash)
}

// SetBatch mocks base method.
func (m *MockUnsubscribeCacheInterface) SetBatch(ctx context.Context, userID string, hashes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBatch", ctx, userID, hashes)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBatch indicates an expected call of SetBatch.
func (mr *MockUnsubscribeCacheInterfaceMockRecorder) SetBatch(ctx, userID, hashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBatch", reflect.TypeOf((*MockUnsubscribeCacheInterface)(nil).SetBatch), ctx, userID, hashes)
}

// MockPendingAttachmentCacheInterface is a mock of PendingAttachmentCacheInterface interface.
type MockPendingAttachmentCacheInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPendingAttachmentCacheInterfaceMockRecorder
	isgomock struct{}
}

// MockPendingAttachmentCacheInterfaceMockRecorder is the mock recorder for MockPendingAttachmentCacheInterface.
type MockPendingAttachmentCacheInterfaceMockRecorder struct {
	mock *MockPendingAttachmentCacheInterface
}

// NewMockPendingAttachmentCacheInterface creates a new mock instance.
func NewMockPendingAttachmentCacheInterface(ctrl *gomock.Controller) *MockPendingAttachmentCacheInterface {
	mock := &MockPendingAttachmentCacheInterface{ctrl: ctrl}
	mock.recorder = &MockPendingAttachmentCacheInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPendingAttachmentCacheInterface) EXPECT() *MockPendingAttachmentCacheInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPendingAttachmentCacheInterface) Delete(ctx context.Context, emailID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, emailID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPendingAttachmentCacheInterfaceMockRecorder) Delete(ctx, emailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPendingAttachmentCacheInterface)(nil).Delete), ctx, emailID)
}

// GetByEmailID mocks base method.
func (m *MockPendingAttachmentCacheInterface) GetByEmailID(ctx context.Context, emailID string) (*redis.PendingAttachmentData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmailID", ctx, emailID)
	ret0, _ := ret[0].(*redis.PendingAttachmentData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmailID indicates an expected call of GetByEmailID.
func (mr *MockPendingAttachmentCacheInterfaceMockRecorder) GetByEmailID(ctx, emailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmailID", reflect.TypeOf((*MockPendingAttachmentCacheInterface)(nil).GetByEmailID), ctx, emailID)
}

// GetByS3Key mocks base method.
func (m *MockPendingAttachmentCacheInterface) GetByS3Key(ctx context.Context, s3Key string) (*redis.PendingAttachmentData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByS3Key", ctx, s3Key)
	ret0, _ := ret[0].(*redis.PendingAttachmentData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByS3Key indicates an expected call of GetByS3Key.
func (mr *MockPendingAttachmentCacheInterfaceMockRecorder) GetByS3Key(ctx, s3Key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByS3Key", reflect.TypeOf((*MockPendingAttachmentCacheInterface)(nil).GetByS3Key), ctx, s3Key)
}

// MarkAttachmentScanned mocks base method.
func (m *MockPendingAttachmentCacheInterface) MarkAttachmentScanned(ctx context.Context, s3Key string) (*redis.PendingAttachmentData, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAttachmentScanned", ctx, s3Key)
	ret0, _ := ret[0].(*redis.PendingAttachmentData)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MarkAttachmentScanned indicates an expected call of MarkAttachmentScanned.
func (mr *MockPendingAttachmentCacheInterfaceMockRecorder) MarkAttachmentScanned(ctx, s3Key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAttachmentScanned", reflect.TypeOf((*MockPendingAttachmentCacheInterface)(nil).MarkAttachmentScanned), ctx, s3Key)
}

// Store mocks base method.
func (m *MockPendingAttachmentCacheInterface) Store(ctx context.Context, data *redis.PendingAttachmentData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockPendingAttachmentCacheInterfaceMockRecorder) Store(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockPendingAttachmentCacheInterface)(nil).Store), ctx, data)
}

// MockWebRiskCacheInterface is a mock of WebRiskCacheInterface interface.
type MockWebRiskCacheInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWebRiskCacheInterfaceMockRecorder
	isgomock struct{}
}

// MockWebRiskCacheInterfaceMockRecorder is the mock recorder for MockWebRiskCacheInterface.
type MockWebRiskCacheInterfaceMockRecorder struct {
	mock *MockWebRiskCacheInterface
}

// NewMockWebRiskCacheInterface creates a new mock instance.
func NewMockWebRiskCacheInterface(ctrl *gomock.Controller) *MockWebRiskCacheInterface {
	mock := &MockWebRiskCacheInterface{ctrl: ctrl}
	mock.recorder = &MockWebRiskCacheInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebRiskCacheInterface) EXPECT() *MockWebRiskCacheInterfaceMockRecorder {
	return m.recorder
}

// CheckURLPrefixes mocks base method.
func (m *MockWebRiskCacheInterface) CheckURLPrefixes(ctx context.Context, hashPrefixes []string) ([]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckURLPrefixes", ctx, hashPrefixes)
	ret0, _ := ret[0].([]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckURLPrefixes indicates an expected call of CheckURLPrefixes.
func (mr *MockWebRiskCacheInterfaceMockRecorder) CheckURLPrefixes(ctx, hashPrefixes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckURLPrefixes", reflect.TypeOf((*MockWebRiskCacheInterface)(nil).CheckURLPrefixes), ctx, hashPrefixes)
}
