package worker

import (
	"context"
	"fmt"

	"time"

	"github.com/riverqueue/river"

	"github.com/emailapi/api/internal/domain"
	"github.com/emailapi/api/internal/external/s3"
	"github.com/emailapi/api/internal/external/ses"
	"github.com/emailapi/api/internal/repository"
)

// SendEmailArgs defines the arguments for the send_email job.
type SendEmailArgs struct {
	From        string            `json:"from"`
	To          []string          `json:"to"`
	Cc          []string          `json:"cc"`
	Bcc         []string          `json:"bcc"`
	Subject     string            `json:"subject"`
	Body        string            `json:"body"` // Plain text
	HTML        string            `json:"html"`
	Attachments []AttachmentMeta  `json:"attachments,omitempty"`
	Metadata    map[string]string `json:"metadata,omitempty"`
}

type AttachmentMeta struct {
	Filename    string `json:"filename"`
	S3Key       string `json:"s3_key"`
	ContentType string `json:"content_type"`
}

func (SendEmailArgs) Kind() string { return "send_email" }

// EmailWorker handles email sending jobs.
type EmailWorker struct {
	river.WorkerDefaults[SendEmailArgs]
	sesClient ses.Client
	s3Client  s3.Client
	chRepo    *repository.EmailRepository
}

func NewEmailWorker(sesClient ses.Client, s3Client s3.Client, chRepo *repository.EmailRepository) *EmailWorker {
	return &EmailWorker{
		sesClient: sesClient,
		s3Client:  s3Client,
		chRepo:    chRepo,
	}
}

func (w *EmailWorker) Work(ctx context.Context, job *river.Job[SendEmailArgs]) error {
	// 1. Download attachments from S3
	/*
		var attachments []ses.Attachment
		for _, att := range job.Args.Attachments {
			data, err := w.s3Client.Download(ctx, att.S3Key)
			if err != nil {
				return fmt.Errorf("failed to download attachment %s: %w", att.Filename, err)
			}
			attachments = append(attachments, ses.Attachment{
				Filename:    att.Filename,
				ContentType: att.ContentType,
				Data:        data,
			})
		}
	*/

	// 2. Send Email via SES
	// TODO: Use actual SendInput with MIME construction
	// For now, mocking the call and result
	/*
		resp, err := w.sesClient.SendEmail(ctx, &sesv2.SendEmailInput{
			// ... construct input ...
		})
		if err != nil {
			// Log failure to ClickHouse?
			return err
		}
		messageID := *resp.MessageId
	*/

	// Mock MessageID for now as SES client integration is partial
	messageID := fmt.Sprintf("ses-%d", time.Now().UnixNano())

	// 3. Log to ClickHouse
	email := &domain.Email{
		// ID: job.Args.ID, // We need to pass the ID or generate one. Usually API generates ID and passes it?
		// Worker args don't have ID currently. Let's assume we use MessageID or generate new.
		// Ideally the job arg should include the TrackingID/EmailID generated by the API.

		ID:        job.ID.String(), // Using Job ID as Email ID for correlation, or generate specific one
		MessageID: messageID,
		From:      job.Args.From,
		To:        job.Args.To,
		// ... other fields
		// UserID: job.Args.UserID, // Args need UserID
	}

	// We need UserID in args to log correctly
	// Let's assume "system" or add UserID to SendEmailArgs

	err := (*w.chRepo).AddEmail(ctx, email, "sent")
	if err != nil {
		fmt.Printf("Failed to log email to ClickHouse: %v\n", err)
		// Don't fail the job just because logging failed? depends on requirement.
	}

	fmt.Printf("Sent email to %v (MsgID: %s)\n", job.Args.To, messageID)
	return nil
}
