// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/service (interfaces: Cache)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_cache.go -package=mocks github.com/emailapi/api/internal/service Cache
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	redis "github.com/emailapi/api/internal/repository/redis"
	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// APIKey mocks base method.
func (m *MockCache) APIKey() redis.APIKeyCacheInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIKey")
	ret0, _ := ret[0].(redis.APIKeyCacheInterface)
	return ret0
}

// APIKey indicates an expected call of APIKey.
func (mr *MockCacheMockRecorder) APIKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIKey", reflect.TypeOf((*MockCache)(nil).APIKey))
}

// Credit mocks base method.
func (m *MockCache) Credit() redis.CreditCacheInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Credit")
	ret0, _ := ret[0].(redis.CreditCacheInterface)
	return ret0
}

// Credit indicates an expected call of Credit.
func (mr *MockCacheMockRecorder) Credit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Credit", reflect.TypeOf((*MockCache)(nil).Credit))
}

// Domain mocks base method.
func (m *MockCache) Domain() redis.DomainCacheInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Domain")
	ret0, _ := ret[0].(redis.DomainCacheInterface)
	return ret0
}

// Domain indicates an expected call of Domain.
func (mr *MockCacheMockRecorder) Domain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Domain", reflect.TypeOf((*MockCache)(nil).Domain))
}

// MX mocks base method.
func (m *MockCache) MX() redis.MXCacheInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MX")
	ret0, _ := ret[0].(redis.MXCacheInterface)
	return ret0
}

// MX indicates an expected call of MX.
func (mr *MockCacheMockRecorder) MX() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MX", reflect.TypeOf((*MockCache)(nil).MX))
}

// PendingAttachment mocks base method.
func (m *MockCache) PendingAttachment() redis.PendingAttachmentCacheInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingAttachment")
	ret0, _ := ret[0].(redis.PendingAttachmentCacheInterface)
	return ret0
}

// PendingAttachment indicates an expected call of PendingAttachment.
func (mr *MockCacheMockRecorder) PendingAttachment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingAttachment", reflect.TypeOf((*MockCache)(nil).PendingAttachment))
}

// Reputation mocks base method.
func (m *MockCache) Reputation() redis.ReputationCacheInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reputation")
	ret0, _ := ret[0].(redis.ReputationCacheInterface)
	return ret0
}

// Reputation indicates an expected call of Reputation.
func (mr *MockCacheMockRecorder) Reputation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reputation", reflect.TypeOf((*MockCache)(nil).Reputation))
}

// Unsubscribe mocks base method.
func (m *MockCache) Unsubscribe() redis.UnsubscribeCacheInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe")
	ret0, _ := ret[0].(redis.UnsubscribeCacheInterface)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockCacheMockRecorder) Unsubscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockCache)(nil).Unsubscribe))
}

// User mocks base method.
func (m *MockCache) User() redis.UserCacheInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User")
	ret0, _ := ret[0].(redis.UserCacheInterface)
	return ret0
}

// User indicates an expected call of User.
func (mr *MockCacheMockRecorder) User() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockCache)(nil).User))
}
