// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/service (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_store.go -package=mocks github.com/emailapi/api/internal/service Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	postgres "github.com/emailapi/api/internal/repository/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// APIKeys mocks base method.
func (m *MockStore) APIKeys() postgres.APIKeyRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIKeys")
	ret0, _ := ret[0].(postgres.APIKeyRepository)
	return ret0
}

// APIKeys indicates an expected call of APIKeys.
func (mr *MockStoreMockRecorder) APIKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIKeys", reflect.TypeOf((*MockStore)(nil).APIKeys))
}

// Close mocks base method.
func (m *MockStore) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStore)(nil).Close))
}

// Domains mocks base method.
func (m *MockStore) Domains() postgres.DomainRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Domains")
	ret0, _ := ret[0].(postgres.DomainRepository)
	return ret0
}

// Domains indicates an expected call of Domains.
func (mr *MockStoreMockRecorder) Domains() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Domains", reflect.TypeOf((*MockStore)(nil).Domains))
}

// Reputation mocks base method.
func (m *MockStore) Reputation() postgres.ReputationRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reputation")
	ret0, _ := ret[0].(postgres.ReputationRepository)
	return ret0
}

// Reputation indicates an expected call of Reputation.
func (mr *MockStoreMockRecorder) Reputation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reputation", reflect.TypeOf((*MockStore)(nil).Reputation))
}

// Unsubscribe mocks base method.
func (m *MockStore) Unsubscribe() postgres.UnsubscribeRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe")
	ret0, _ := ret[0].(postgres.UnsubscribeRepository)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockStoreMockRecorder) Unsubscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockStore)(nil).Unsubscribe))
}

// Users mocks base method.
func (m *MockStore) Users() postgres.UserRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Users")
	ret0, _ := ret[0].(postgres.UserRepository)
	return ret0
}

// Users indicates an expected call of Users.
func (mr *MockStoreMockRecorder) Users() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Users", reflect.TypeOf((*MockStore)(nil).Users))
}
