// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/service (interfaces: Analytics)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_analytics.go -package=mocks github.com/emailapi/api/internal/service Analytics
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	tinybird "github.com/emailapi/api/internal/repository/tinybird"
	gomock "go.uber.org/mock/gomock"
)

// MockAnalytics is a mock of Analytics interface.
type MockAnalytics struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsMockRecorder
	isgomock struct{}
}

// MockAnalyticsMockRecorder is the mock recorder for MockAnalytics.
type MockAnalyticsMockRecorder struct {
	mock *MockAnalytics
}

// NewMockAnalytics creates a new mock instance.
func NewMockAnalytics(ctrl *gomock.Controller) *MockAnalytics {
	mock := &MockAnalytics{ctrl: ctrl}
	mock.recorder = &MockAnalyticsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalytics) EXPECT() *MockAnalyticsMockRecorder {
	return m.recorder
}

// Activity mocks base method.
func (m *MockAnalytics) Activity() tinybird.ActivityRepositoryInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activity")
	ret0, _ := ret[0].(tinybird.ActivityRepositoryInterface)
	return ret0
}

// Activity indicates an expected call of Activity.
func (mr *MockAnalyticsMockRecorder) Activity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activity", reflect.TypeOf((*MockAnalytics)(nil).Activity))
}

// Email mocks base method.
func (m *MockAnalytics) Email() tinybird.EmailRepositoryInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Email")
	ret0, _ := ret[0].(tinybird.EmailRepositoryInterface)
	return ret0
}

// Email indicates an expected call of Email.
func (mr *MockAnalyticsMockRecorder) Email() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Email", reflect.TypeOf((*MockAnalytics)(nil).Email))
}
