// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/service (interfaces: QueueClient,SenderValidator,UnsubscribeManager,ReputationRecorder,SuppressionManager)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service_interfaces.go -package=mocks github.com/emailapi/api/internal/service QueueClient,SenderValidator,UnsubscribeManager,ReputationRecorder,SuppressionManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/emailapi/api/internal/domain"
	suppression "github.com/emailapi/api/internal/repository/suppression"
	river "github.com/riverqueue/river"
	rivertype "github.com/riverqueue/river/rivertype"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueClient is a mock of QueueClient interface.
type MockQueueClient struct {
	ctrl     *gomock.Controller
	recorder *MockQueueClientMockRecorder
	isgomock struct{}
}

// MockQueueClientMockRecorder is the mock recorder for MockQueueClient.
type MockQueueClientMockRecorder struct {
	mock *MockQueueClient
}

// NewMockQueueClient creates a new mock instance.
func NewMockQueueClient(ctrl *gomock.Controller) *MockQueueClient {
	mock := &MockQueueClient{ctrl: ctrl}
	mock.recorder = &MockQueueClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueClient) EXPECT() *MockQueueClientMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockQueueClient) Insert(ctx context.Context, args river.JobArgs, opts *river.InsertOpts) (*rivertype.JobInsertResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, args, opts)
	ret0, _ := ret[0].(*rivertype.JobInsertResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockQueueClientMockRecorder) Insert(ctx, args, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockQueueClient)(nil).Insert), ctx, args, opts)
}

// MockSenderValidator is a mock of SenderValidator interface.
type MockSenderValidator struct {
	ctrl     *gomock.Controller
	recorder *MockSenderValidatorMockRecorder
	isgomock struct{}
}

// MockSenderValidatorMockRecorder is the mock recorder for MockSenderValidator.
type MockSenderValidatorMockRecorder struct {
	mock *MockSenderValidator
}

// NewMockSenderValidator creates a new mock instance.
func NewMockSenderValidator(ctrl *gomock.Controller) *MockSenderValidator {
	mock := &MockSenderValidator{ctrl: ctrl}
	mock.recorder = &MockSenderValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSenderValidator) EXPECT() *MockSenderValidatorMockRecorder {
	return m.recorder
}

// ValidateSendEmail mocks base method.
func (m *MockSenderValidator) ValidateSendEmail(ctx context.Context, userID, from string, to, cc, bcc []string, body, html string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSendEmail", ctx, userID, from, to, cc, bcc, body, html)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSendEmail indicates an expected call of ValidateSendEmail.
func (mr *MockSenderValidatorMockRecorder) ValidateSendEmail(ctx, userID, from, to, cc, bcc, body, html any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSendEmail", reflect.TypeOf((*MockSenderValidator)(nil).ValidateSendEmail), ctx, userID, from, to, cc, bcc, body, html)
}

// MockUnsubscribeManager is a mock of UnsubscribeManager interface.
type MockUnsubscribeManager struct {
	ctrl     *gomock.Controller
	recorder *MockUnsubscribeManagerMockRecorder
	isgomock struct{}
}

// MockUnsubscribeManagerMockRecorder is the mock recorder for MockUnsubscribeManager.
type MockUnsubscribeManagerMockRecorder struct {
	mock *MockUnsubscribeManager
}

// NewMockUnsubscribeManager creates a new mock instance.
func NewMockUnsubscribeManager(ctrl *gomock.Controller) *MockUnsubscribeManager {
	mock := &MockUnsubscribeManager{ctrl: ctrl}
	mock.recorder = &MockUnsubscribeManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsubscribeManager) EXPECT() *MockUnsubscribeManagerMockRecorder {
	return m.recorder
}

// BaseURL mocks base method.
func (m *MockUnsubscribeManager) BaseURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// BaseURL indicates an expected call of BaseURL.
func (mr *MockUnsubscribeManagerMockRecorder) BaseURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseURL", reflect.TypeOf((*MockUnsubscribeManager)(nil).BaseURL))
}

// CheckBatch mocks base method.
func (m *MockUnsubscribeManager) CheckBatch(ctx context.Context, userID string, emails []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBatch", ctx, userID, emails)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBatch indicates an expected call of CheckBatch.
func (mr *MockUnsubscribeManagerMockRecorder) CheckBatch(ctx, userID, emails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBatch", reflect.TypeOf((*MockUnsubscribeManager)(nil).CheckBatch), ctx, userID, emails)
}

// GenerateLink mocks base method.
func (m *MockUnsubscribeManager) GenerateLink(userID, recipientEmail, emailID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateLink", userID, recipientEmail, emailID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateLink indicates an expected call of GenerateLink.
func (mr *MockUnsubscribeManagerMockRecorder) GenerateLink(userID, recipientEmail, emailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateLink", reflect.TypeOf((*MockUnsubscribeManager)(nil).GenerateLink), userID, recipientEmail, emailID)
}

// TokenSecret mocks base method.
func (m *MockUnsubscribeManager) TokenSecret() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenSecret")
	ret0, _ := ret[0].(string)
	return ret0
}

// TokenSecret indicates an expected call of TokenSecret.
func (mr *MockUnsubscribeManagerMockRecorder) TokenSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenSecret", reflect.TypeOf((*MockUnsubscribeManager)(nil).TokenSecret))
}

// MockReputationRecorder is a mock of ReputationRecorder interface.
type MockReputationRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockReputationRecorderMockRecorder
	isgomock struct{}
}

// MockReputationRecorderMockRecorder is the mock recorder for MockReputationRecorder.
type MockReputationRecorderMockRecorder struct {
	mock *MockReputationRecorder
}

// NewMockReputationRecorder creates a new mock instance.
func NewMockReputationRecorder(ctrl *gomock.Controller) *MockReputationRecorder {
	mock := &MockReputationRecorder{ctrl: ctrl}
	mock.recorder = &MockReputationRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReputationRecorder) EXPECT() *MockReputationRecorderMockRecorder {
	return m.recorder
}

// RecordBounceIncident mocks base method.
func (m *MockReputationRecorder) RecordBounceIncident(ctx context.Context, userID, messageID, bounceType, bounceSubType string, recipients []domain.BounceRecipient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordBounceIncident", ctx, userID, messageID, bounceType, bounceSubType, recipients)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordBounceIncident indicates an expected call of RecordBounceIncident.
func (mr *MockReputationRecorderMockRecorder) RecordBounceIncident(ctx, userID, messageID, bounceType, bounceSubType, recipients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordBounceIncident", reflect.TypeOf((*MockReputationRecorder)(nil).RecordBounceIncident), ctx, userID, messageID, bounceType, bounceSubType, recipients)
}

// RecordComplaintIncident mocks base method.
func (m *MockReputationRecorder) RecordComplaintIncident(ctx context.Context, userID, messageID, feedbackType string, recipientEmails []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordComplaintIncident", ctx, userID, messageID, feedbackType, recipientEmails)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordComplaintIncident indicates an expected call of RecordComplaintIncident.
func (mr *MockReputationRecorderMockRecorder) RecordComplaintIncident(ctx, userID, messageID, feedbackType, recipientEmails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordComplaintIncident", reflect.TypeOf((*MockReputationRecorder)(nil).RecordComplaintIncident), ctx, userID, messageID, feedbackType, recipientEmails)
}

// MockSuppressionManager is a mock of SuppressionManager interface.
type MockSuppressionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSuppressionManagerMockRecorder
	isgomock struct{}
}

// MockSuppressionManagerMockRecorder is the mock recorder for MockSuppressionManager.
type MockSuppressionManagerMockRecorder struct {
	mock *MockSuppressionManager
}

// NewMockSuppressionManager creates a new mock instance.
func NewMockSuppressionManager(ctrl *gomock.Controller) *MockSuppressionManager {
	mock := &MockSuppressionManager{ctrl: ctrl}
	mock.recorder = &MockSuppressionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuppressionManager) EXPECT() *MockSuppressionManagerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockSuppressionManager) Add(ctx context.Context, entry *suppression.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockSuppressionManagerMockRecorder) Add(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockSuppressionManager)(nil).Add), ctx, entry)
}
