version: v2
inputs:
  - directory: public
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      module: buf.build/emailapi/public
      value: github.com/emailapi/api/gen

plugins:
  # The magic plugin for Connect + OpenAPI
  - remote: buf.build/community/sudorandom-connect-openapi
    out: ../apps/docs/api-reference
    opt:
      - format=json
      - path=openapi.json
