// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_key.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveApiKeysByUserID = `-- name: CountActiveApiKeysByUserID :one
SELECT COUNT(*) FROM api_keys WHERE user_id = $1 AND is_active = true
`

func (q *Queries) CountActiveApiKeysByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveApiKeysByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countApiKeysByUserID = `-- name: CountApiKeysByUserID :one
SELECT COUNT(*) FROM api_keys WHERE user_id = $1
`

func (q *Queries) CountApiKeysByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countApiKeysByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (id, user_id, name, key_hash, key_prefix, scopes, environment, is_active, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, name, key_hash, key_prefix, scopes, environment, is_active, last_used_at, expires_at, created_at, updated_at
`

type CreateApiKeyParams struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Name        string             `json:"name"`
	KeyHash     string             `json:"key_hash"`
	KeyPrefix   string             `json:"key_prefix"`
	Scopes      []string           `json:"scopes"`
	Environment string             `json:"environment"`
	IsActive    bool               `json:"is_active"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Scopes,
		arg.Environment,
		arg.IsActive,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.Environment,
		&i.IsActive,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApiKey = `-- name: DeleteApiKey :exec
DELETE FROM api_keys WHERE id = $1
`

func (q *Queries) DeleteApiKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteApiKey, id)
	return err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, user_id, name, key_hash, key_prefix, scopes, environment, is_active, last_used_at, expires_at, created_at, updated_at
FROM api_keys WHERE key_hash = $1 AND is_active = true
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.Environment,
		&i.IsActive,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApiKeyByID = `-- name: GetApiKeyByID :one
SELECT id, user_id, name, key_hash, key_prefix, scopes, environment, is_active, last_used_at, expires_at, created_at, updated_at
FROM api_keys WHERE id = $1
`

func (q *Queries) GetApiKeyByID(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.Environment,
		&i.IsActive,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApiKeyByPrefix = `-- name: GetApiKeyByPrefix :one
SELECT id, user_id, name, key_hash, key_prefix, scopes, environment, is_active, last_used_at, expires_at, created_at, updated_at
FROM api_keys WHERE key_prefix = $1
`

func (q *Queries) GetApiKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByPrefix, keyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.Environment,
		&i.IsActive,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApiKeysByUserID = `-- name: ListApiKeysByUserID :many
SELECT id, user_id, name, key_prefix, scopes, environment, is_active, last_used_at, expires_at, created_at, updated_at
FROM api_keys WHERE user_id = $1
ORDER BY created_at DESC
`

type ListApiKeysByUserIDRow struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Name        string             `json:"name"`
	KeyPrefix   string             `json:"key_prefix"`
	Scopes      []string           `json:"scopes"`
	Environment string             `json:"environment"`
	IsActive    bool               `json:"is_active"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListApiKeysByUserID(ctx context.Context, userID string) ([]ListApiKeysByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listApiKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiKeysByUserIDRow
	for rows.Next() {
		var i ListApiKeysByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.Scopes,
			&i.Environment,
			&i.IsActive,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiKeysByUserIDPaginated = `-- name: ListApiKeysByUserIDPaginated :many
SELECT id, user_id, name, key_prefix, scopes, environment, is_active, last_used_at, expires_at, created_at, updated_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListApiKeysByUserIDPaginatedParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListApiKeysByUserIDPaginatedRow struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Name        string             `json:"name"`
	KeyPrefix   string             `json:"key_prefix"`
	Scopes      []string           `json:"scopes"`
	Environment string             `json:"environment"`
	IsActive    bool               `json:"is_active"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListApiKeysByUserIDPaginated(ctx context.Context, arg ListApiKeysByUserIDPaginatedParams) ([]ListApiKeysByUserIDPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listApiKeysByUserIDPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiKeysByUserIDPaginatedRow
	for rows.Next() {
		var i ListApiKeysByUserIDPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.Scopes,
			&i.Environment,
			&i.IsActive,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :one
UPDATE api_keys SET is_active = false, updated_at = NOW() WHERE id = $1
RETURNING id, user_id, name, key_hash, key_prefix, scopes, environment, is_active, last_used_at, expires_at, created_at, updated_at
`

func (q *Queries) RevokeApiKey(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeApiKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.Environment,
		&i.IsActive,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApiKey = `-- name: UpdateApiKey :one
UPDATE api_keys SET
    name = $2,
    scopes = $3,
    is_active = $4,
    expires_at = $5,
    updated_at = $6
WHERE id = $1
RETURNING id, user_id, name, key_hash, key_prefix, scopes, environment, is_active, last_used_at, expires_at, created_at, updated_at
`

type UpdateApiKeyParams struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Scopes    []string           `json:"scopes"`
	IsActive  bool               `json:"is_active"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateApiKey(ctx context.Context, arg UpdateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateApiKey,
		arg.ID,
		arg.Name,
		arg.Scopes,
		arg.IsActive,
		arg.ExpiresAt,
		arg.UpdatedAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.Environment,
		&i.IsActive,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApiKeyLastUsed = `-- name: UpdateApiKeyLastUsed :exec
UPDATE api_keys SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateApiKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateApiKeyLastUsed, id)
	return err
}
