// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: domain.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDomain = `-- name: CreateDomain :exec
INSERT INTO domains (
    id, user_id, domain_name, status, verified_for_sending,
    dkim_tokens, dkim_status, mail_from_domain, mail_from_status,
    region, created_at, updated_at, last_verified_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
`

type CreateDomainParams struct {
	ID                 string             `json:"id"`
	UserID             string             `json:"user_id"`
	DomainName         string             `json:"domain_name"`
	Status             string             `json:"status"`
	VerifiedForSending bool               `json:"verified_for_sending"`
	DkimTokens         []string           `json:"dkim_tokens"`
	DkimStatus         string             `json:"dkim_status"`
	MailFromDomain     pgtype.Text        `json:"mail_from_domain"`
	MailFromStatus     pgtype.Text        `json:"mail_from_status"`
	Region             string             `json:"region"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	LastVerifiedAt     pgtype.Timestamptz `json:"last_verified_at"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) error {
	_, err := q.db.Exec(ctx, createDomain,
		arg.ID,
		arg.UserID,
		arg.DomainName,
		arg.Status,
		arg.VerifiedForSending,
		arg.DkimTokens,
		arg.DkimStatus,
		arg.MailFromDomain,
		arg.MailFromStatus,
		arg.Region,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastVerifiedAt,
	)
	return err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains WHERE id = $1
`

func (q *Queries) DeleteDomain(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDomain, id)
	return err
}

const getDomainByID = `-- name: GetDomainByID :one
SELECT id, user_id, domain_name, status, verified_for_sending, dkim_tokens, dkim_status, mail_from_domain, mail_from_status, region, last_verified_at, created_at, updated_at FROM domains WHERE id = $1
`

func (q *Queries) GetDomainByID(ctx context.Context, id string) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByID, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DomainName,
		&i.Status,
		&i.VerifiedForSending,
		&i.DkimTokens,
		&i.DkimStatus,
		&i.MailFromDomain,
		&i.MailFromStatus,
		&i.Region,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainByName = `-- name: GetDomainByName :one
SELECT id, user_id, domain_name, status, verified_for_sending, dkim_tokens, dkim_status, mail_from_domain, mail_from_status, region, last_verified_at, created_at, updated_at FROM domains WHERE user_id = $1 AND domain_name = $2
`

type GetDomainByNameParams struct {
	UserID     string `json:"user_id"`
	DomainName string `json:"domain_name"`
}

func (q *Queries) GetDomainByName(ctx context.Context, arg GetDomainByNameParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByName, arg.UserID, arg.DomainName)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DomainName,
		&i.Status,
		&i.VerifiedForSending,
		&i.DkimTokens,
		&i.DkimStatus,
		&i.MailFromDomain,
		&i.MailFromStatus,
		&i.Region,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainsByUserID = `-- name: GetDomainsByUserID :many
SELECT id, user_id, domain_name, status, verified_for_sending, dkim_tokens, dkim_status, mail_from_domain, mail_from_status, region, last_verified_at, created_at, updated_at FROM domains WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetDomainsByUserID(ctx context.Context, userID string) ([]Domain, error) {
	rows, err := q.db.Query(ctx, getDomainsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DomainName,
			&i.Status,
			&i.VerifiedForSending,
			&i.DkimTokens,
			&i.DkimStatus,
			&i.MailFromDomain,
			&i.MailFromStatus,
			&i.Region,
			&i.LastVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleDomains = `-- name: GetStaleDomains :many
SELECT id, user_id, domain_name, status, verified_for_sending, dkim_tokens, dkim_status, mail_from_domain, mail_from_status, region, last_verified_at, created_at, updated_at FROM domains 
WHERE last_verified_at IS NULL 
   OR last_verified_at < NOW() - INTERVAL '5 minutes'
ORDER BY last_verified_at ASC NULLS FIRST
LIMIT $1
`

// Get domains that need verification refresh (never verified or older than threshold)
func (q *Queries) GetStaleDomains(ctx context.Context, limit int32) ([]Domain, error) {
	rows, err := q.db.Query(ctx, getStaleDomains, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DomainName,
			&i.Status,
			&i.VerifiedForSending,
			&i.DkimTokens,
			&i.DkimStatus,
			&i.MailFromDomain,
			&i.MailFromStatus,
			&i.Region,
			&i.LastVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDomain = `-- name: UpdateDomain :exec
UPDATE domains SET
    status = $2,
    verified_for_sending = $3,
    dkim_tokens = $4,
    dkim_status = $5,
    mail_from_domain = $6,
    mail_from_status = $7,
    updated_at = NOW(),
    last_verified_at = $8
WHERE id = $1
`

type UpdateDomainParams struct {
	ID                 string             `json:"id"`
	Status             string             `json:"status"`
	VerifiedForSending bool               `json:"verified_for_sending"`
	DkimTokens         []string           `json:"dkim_tokens"`
	DkimStatus         string             `json:"dkim_status"`
	MailFromDomain     pgtype.Text        `json:"mail_from_domain"`
	MailFromStatus     pgtype.Text        `json:"mail_from_status"`
	LastVerifiedAt     pgtype.Timestamptz `json:"last_verified_at"`
}

func (q *Queries) UpdateDomain(ctx context.Context, arg UpdateDomainParams) error {
	_, err := q.db.Exec(ctx, updateDomain,
		arg.ID,
		arg.Status,
		arg.VerifiedForSending,
		arg.DkimTokens,
		arg.DkimStatus,
		arg.MailFromDomain,
		arg.MailFromStatus,
		arg.LastVerifiedAt,
	)
	return err
}
