// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: email.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEmailsByUserID = `-- name: CountEmailsByUserID :one
SELECT COUNT(*) FROM emails WHERE user_id = $1
`

func (q *Queries) CountEmailsByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countEmailsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails (
    id, from_address, to_addresses, cc_addresses, bcc_addresses,
    subject, body, html_body, status, provider_id, user_id, webhook_id,
    metadata, scheduled_at, sent_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
) RETURNING id, from_address, to_addresses, cc_addresses, bcc_addresses, subject, body, html_body, status, provider_id, user_id, webhook_id, metadata, scheduled_at, sent_at, created_at, updated_at
`

type CreateEmailParams struct {
	ID           string             `json:"id"`
	FromAddress  string             `json:"from_address"`
	ToAddresses  []string           `json:"to_addresses"`
	CcAddresses  []string           `json:"cc_addresses"`
	BccAddresses []string           `json:"bcc_addresses"`
	Subject      string             `json:"subject"`
	Body         pgtype.Text        `json:"body"`
	HtmlBody     pgtype.Text        `json:"html_body"`
	Status       string             `json:"status"`
	ProviderID   pgtype.Text        `json:"provider_id"`
	UserID       string             `json:"user_id"`
	WebhookID    pgtype.Text        `json:"webhook_id"`
	Metadata     []byte             `json:"metadata"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, createEmail,
		arg.ID,
		arg.FromAddress,
		arg.ToAddresses,
		arg.CcAddresses,
		arg.BccAddresses,
		arg.Subject,
		arg.Body,
		arg.HtmlBody,
		arg.Status,
		arg.ProviderID,
		arg.UserID,
		arg.WebhookID,
		arg.Metadata,
		arg.ScheduledAt,
		arg.SentAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.FromAddress,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.Body,
		&i.HtmlBody,
		&i.Status,
		&i.ProviderID,
		&i.UserID,
		&i.WebhookID,
		&i.Metadata,
		&i.ScheduledAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailByID = `-- name: GetEmailByID :one
SELECT id, from_address, to_addresses, cc_addresses, bcc_addresses, subject, body, html_body, status, provider_id, user_id, webhook_id, metadata, scheduled_at, sent_at, created_at, updated_at FROM emails WHERE id = $1
`

func (q *Queries) GetEmailByID(ctx context.Context, id string) (Email, error) {
	row := q.db.QueryRow(ctx, getEmailByID, id)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.FromAddress,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.Body,
		&i.HtmlBody,
		&i.Status,
		&i.ProviderID,
		&i.UserID,
		&i.WebhookID,
		&i.Metadata,
		&i.ScheduledAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailsByUserID = `-- name: GetEmailsByUserID :many
SELECT id, from_address, to_addresses, cc_addresses, bcc_addresses, subject, body, html_body, status, provider_id, user_id, webhook_id, metadata, scheduled_at, sent_at, created_at, updated_at FROM emails 
WHERE user_id = $1 
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type GetEmailsByUserIDParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetEmailsByUserID(ctx context.Context, arg GetEmailsByUserIDParams) ([]Email, error) {
	rows, err := q.db.Query(ctx, getEmailsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Email
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.ID,
			&i.FromAddress,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.BccAddresses,
			&i.Subject,
			&i.Body,
			&i.HtmlBody,
			&i.Status,
			&i.ProviderID,
			&i.UserID,
			&i.WebhookID,
			&i.Metadata,
			&i.ScheduledAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmail = `-- name: UpdateEmail :one
UPDATE emails SET
    from_address = $2,
    to_addresses = $3,
    cc_addresses = $4,
    bcc_addresses = $5,
    subject = $6,
    body = $7,
    html_body = $8,
    status = $9,
    provider_id = $10,
    webhook_id = $11,
    metadata = $12,
    scheduled_at = $13,
    sent_at = $14,
    updated_at = $15
WHERE id = $1
RETURNING id, from_address, to_addresses, cc_addresses, bcc_addresses, subject, body, html_body, status, provider_id, user_id, webhook_id, metadata, scheduled_at, sent_at, created_at, updated_at
`

type UpdateEmailParams struct {
	ID           string             `json:"id"`
	FromAddress  string             `json:"from_address"`
	ToAddresses  []string           `json:"to_addresses"`
	CcAddresses  []string           `json:"cc_addresses"`
	BccAddresses []string           `json:"bcc_addresses"`
	Subject      string             `json:"subject"`
	Body         pgtype.Text        `json:"body"`
	HtmlBody     pgtype.Text        `json:"html_body"`
	Status       string             `json:"status"`
	ProviderID   pgtype.Text        `json:"provider_id"`
	WebhookID    pgtype.Text        `json:"webhook_id"`
	Metadata     []byte             `json:"metadata"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, updateEmail,
		arg.ID,
		arg.FromAddress,
		arg.ToAddresses,
		arg.CcAddresses,
		arg.BccAddresses,
		arg.Subject,
		arg.Body,
		arg.HtmlBody,
		arg.Status,
		arg.ProviderID,
		arg.WebhookID,
		arg.Metadata,
		arg.ScheduledAt,
		arg.SentAt,
		arg.UpdatedAt,
	)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.FromAddress,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.Body,
		&i.HtmlBody,
		&i.Status,
		&i.ProviderID,
		&i.UserID,
		&i.WebhookID,
		&i.Metadata,
		&i.ScheduledAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmailStatus = `-- name: UpdateEmailStatus :exec
UPDATE emails SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateEmailStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateEmailStatus(ctx context.Context, arg UpdateEmailStatusParams) error {
	_, err := q.db.Exec(ctx, updateEmailStatus, arg.ID, arg.Status)
	return err
}
