// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: email.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkAllAttachmentsScanned = `-- name: CheckAllAttachmentsScanned :one
SELECT 
    COUNT(*) FILTER (WHERE scan_status IN ('pending', 'scanning')) = 0 AS all_scanned,
    COUNT(*) FILTER (WHERE scan_status = 'clean') = COUNT(*) AS all_clean,
    COUNT(*) FILTER (WHERE scan_status = 'threats_found') > 0 AS has_threats
FROM email_attachments 
WHERE email_id = $1
`

type CheckAllAttachmentsScannedRow struct {
	AllScanned bool `json:"all_scanned"`
	AllClean   bool `json:"all_clean"`
	HasThreats bool `json:"has_threats"`
}

func (q *Queries) CheckAllAttachmentsScanned(ctx context.Context, emailID string) (CheckAllAttachmentsScannedRow, error) {
	row := q.db.QueryRow(ctx, checkAllAttachmentsScanned, emailID)
	var i CheckAllAttachmentsScannedRow
	err := row.Scan(&i.AllScanned, &i.AllClean, &i.HasThreats)
	return i, err
}

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails (
    id, user_id, from_address, to_addresses, cc_addresses, bcc_addresses,
    subject, body, html, status, metadata, scheduled_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, user_id, from_address, to_addresses, cc_addresses, bcc_addresses, subject, body, html, status, provider_id, metadata, scheduled_at, sent_at, error_message, created_at, updated_at
`

type CreateEmailParams struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	FromAddress  string             `json:"from_address"`
	ToAddresses  []string           `json:"to_addresses"`
	CcAddresses  []string           `json:"cc_addresses"`
	BccAddresses []string           `json:"bcc_addresses"`
	Subject      string             `json:"subject"`
	Body         pgtype.Text        `json:"body"`
	Html         pgtype.Text        `json:"html"`
	Status       string             `json:"status"`
	Metadata     []byte             `json:"metadata"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, createEmail,
		arg.ID,
		arg.UserID,
		arg.FromAddress,
		arg.ToAddresses,
		arg.CcAddresses,
		arg.BccAddresses,
		arg.Subject,
		arg.Body,
		arg.Html,
		arg.Status,
		arg.Metadata,
		arg.ScheduledAt,
	)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAddress,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.Body,
		&i.Html,
		&i.Status,
		&i.ProviderID,
		&i.Metadata,
		&i.ScheduledAt,
		&i.SentAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmailAttachment = `-- name: CreateEmailAttachment :one
INSERT INTO email_attachments (
    id, email_id, filename, content_type, s3_key, size_bytes, scan_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, email_id, filename, content_type, s3_key, size_bytes, scan_status, scan_checked_at, created_at
`

type CreateEmailAttachmentParams struct {
	ID          string `json:"id"`
	EmailID     string `json:"email_id"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	S3Key       string `json:"s3_key"`
	SizeBytes   int64  `json:"size_bytes"`
	ScanStatus  string `json:"scan_status"`
}

func (q *Queries) CreateEmailAttachment(ctx context.Context, arg CreateEmailAttachmentParams) (EmailAttachment, error) {
	row := q.db.QueryRow(ctx, createEmailAttachment,
		arg.ID,
		arg.EmailID,
		arg.Filename,
		arg.ContentType,
		arg.S3Key,
		arg.SizeBytes,
		arg.ScanStatus,
	)
	var i EmailAttachment
	err := row.Scan(
		&i.ID,
		&i.EmailID,
		&i.Filename,
		&i.ContentType,
		&i.S3Key,
		&i.SizeBytes,
		&i.ScanStatus,
		&i.ScanCheckedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachmentsByEmailID = `-- name: DeleteAttachmentsByEmailID :exec
DELETE FROM email_attachments WHERE email_id = $1
`

func (q *Queries) DeleteAttachmentsByEmailID(ctx context.Context, emailID string) error {
	_, err := q.db.Exec(ctx, deleteAttachmentsByEmailID, emailID)
	return err
}

const deleteEmail = `-- name: DeleteEmail :exec
DELETE FROM emails WHERE id = $1
`

func (q *Queries) DeleteEmail(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEmail, id)
	return err
}

const getAttachmentByS3Key = `-- name: GetAttachmentByS3Key :one
SELECT id, email_id, filename, content_type, s3_key, size_bytes, scan_status, scan_checked_at, created_at FROM email_attachments WHERE s3_key = $1
`

func (q *Queries) GetAttachmentByS3Key(ctx context.Context, s3Key string) (EmailAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByS3Key, s3Key)
	var i EmailAttachment
	err := row.Scan(
		&i.ID,
		&i.EmailID,
		&i.Filename,
		&i.ContentType,
		&i.S3Key,
		&i.SizeBytes,
		&i.ScanStatus,
		&i.ScanCheckedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentsByEmailID = `-- name: GetAttachmentsByEmailID :many
SELECT id, email_id, filename, content_type, s3_key, size_bytes, scan_status, scan_checked_at, created_at FROM email_attachments WHERE email_id = $1
`

func (q *Queries) GetAttachmentsByEmailID(ctx context.Context, emailID string) ([]EmailAttachment, error) {
	rows, err := q.db.Query(ctx, getAttachmentsByEmailID, emailID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailAttachment
	for rows.Next() {
		var i EmailAttachment
		if err := rows.Scan(
			&i.ID,
			&i.EmailID,
			&i.Filename,
			&i.ContentType,
			&i.S3Key,
			&i.SizeBytes,
			&i.ScanStatus,
			&i.ScanCheckedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailByID = `-- name: GetEmailByID :one
SELECT id, user_id, from_address, to_addresses, cc_addresses, bcc_addresses, subject, body, html, status, provider_id, metadata, scheduled_at, sent_at, error_message, created_at, updated_at FROM emails WHERE id = $1
`

func (q *Queries) GetEmailByID(ctx context.Context, id string) (Email, error) {
	row := q.db.QueryRow(ctx, getEmailByID, id)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAddress,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.Body,
		&i.Html,
		&i.Status,
		&i.ProviderID,
		&i.Metadata,
		&i.ScheduledAt,
		&i.SentAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailsByUserID = `-- name: GetEmailsByUserID :many
SELECT id, user_id, from_address, to_addresses, cc_addresses, bcc_addresses, subject, body, html, status, provider_id, metadata, scheduled_at, sent_at, error_message, created_at, updated_at FROM emails 
WHERE user_id = $1 
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type GetEmailsByUserIDParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetEmailsByUserID(ctx context.Context, arg GetEmailsByUserIDParams) ([]Email, error) {
	rows, err := q.db.Query(ctx, getEmailsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Email
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FromAddress,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.BccAddresses,
			&i.Subject,
			&i.Body,
			&i.Html,
			&i.Status,
			&i.ProviderID,
			&i.Metadata,
			&i.ScheduledAt,
			&i.SentAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailsWithPendingAttachments = `-- name: GetEmailsWithPendingAttachments :many
SELECT DISTINCT e.id, e.user_id, e.from_address, e.to_addresses, e.cc_addresses, e.bcc_addresses, e.subject, e.body, e.html, e.status, e.provider_id, e.metadata, e.scheduled_at, e.sent_at, e.error_message, e.created_at, e.updated_at FROM emails e
JOIN email_attachments ea ON ea.email_id = e.id
WHERE ea.scan_status IN ('pending', 'scanning')
ORDER BY e.created_at
`

func (q *Queries) GetEmailsWithPendingAttachments(ctx context.Context) ([]Email, error) {
	rows, err := q.db.Query(ctx, getEmailsWithPendingAttachments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Email
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FromAddress,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.BccAddresses,
			&i.Subject,
			&i.Body,
			&i.Html,
			&i.Status,
			&i.ProviderID,
			&i.Metadata,
			&i.ScheduledAt,
			&i.SentAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttachmentScanStatus = `-- name: UpdateAttachmentScanStatus :one
UPDATE email_attachments 
SET scan_status = $2, scan_checked_at = NOW() 
WHERE id = $1 
RETURNING id, email_id, filename, content_type, s3_key, size_bytes, scan_status, scan_checked_at, created_at
`

type UpdateAttachmentScanStatusParams struct {
	ID         string `json:"id"`
	ScanStatus string `json:"scan_status"`
}

func (q *Queries) UpdateAttachmentScanStatus(ctx context.Context, arg UpdateAttachmentScanStatusParams) (EmailAttachment, error) {
	row := q.db.QueryRow(ctx, updateAttachmentScanStatus, arg.ID, arg.ScanStatus)
	var i EmailAttachment
	err := row.Scan(
		&i.ID,
		&i.EmailID,
		&i.Filename,
		&i.ContentType,
		&i.S3Key,
		&i.SizeBytes,
		&i.ScanStatus,
		&i.ScanCheckedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateEmailSent = `-- name: UpdateEmailSent :one
UPDATE emails 
SET status = 'sent', provider_id = $2, sent_at = NOW(), updated_at = NOW() 
WHERE id = $1 
RETURNING id, user_id, from_address, to_addresses, cc_addresses, bcc_addresses, subject, body, html, status, provider_id, metadata, scheduled_at, sent_at, error_message, created_at, updated_at
`

type UpdateEmailSentParams struct {
	ID         string      `json:"id"`
	ProviderID pgtype.Text `json:"provider_id"`
}

func (q *Queries) UpdateEmailSent(ctx context.Context, arg UpdateEmailSentParams) (Email, error) {
	row := q.db.QueryRow(ctx, updateEmailSent, arg.ID, arg.ProviderID)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAddress,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.Body,
		&i.Html,
		&i.Status,
		&i.ProviderID,
		&i.Metadata,
		&i.ScheduledAt,
		&i.SentAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmailStatus = `-- name: UpdateEmailStatus :one
UPDATE emails 
SET status = $2, error_message = $3, updated_at = NOW() 
WHERE id = $1 
RETURNING id, user_id, from_address, to_addresses, cc_addresses, bcc_addresses, subject, body, html, status, provider_id, metadata, scheduled_at, sent_at, error_message, created_at, updated_at
`

type UpdateEmailStatusParams struct {
	ID           string      `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateEmailStatus(ctx context.Context, arg UpdateEmailStatusParams) (Email, error) {
	row := q.db.QueryRow(ctx, updateEmailStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAddress,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.Body,
		&i.Html,
		&i.Status,
		&i.ProviderID,
		&i.Metadata,
		&i.ScheduledAt,
		&i.SentAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
