// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Email struct {
	ID           string             `json:"id"`
	FromAddress  string             `json:"from_address"`
	ToAddresses  []string           `json:"to_addresses"`
	CcAddresses  []string           `json:"cc_addresses"`
	BccAddresses []string           `json:"bcc_addresses"`
	Subject      string             `json:"subject"`
	Body         pgtype.Text        `json:"body"`
	HtmlBody     pgtype.Text        `json:"html_body"`
	Status       string             `json:"status"`
	ProviderID   pgtype.Text        `json:"provider_id"`
	UserID       string             `json:"user_id"`
	WebhookID    pgtype.Text        `json:"webhook_id"`
	Metadata     []byte             `json:"metadata"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	ApiKeyHash   pgtype.Text        `json:"api_key_hash"`
	ApiKeyPrefix pgtype.Text        `json:"api_key_prefix"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Webhook struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Name        string             `json:"name"`
	Url         string             `json:"url"`
	SecretHash  string             `json:"secret_hash"`
	Events      []string           `json:"events"`
	IsActive    bool               `json:"is_active"`
	RetryCount  int32              `json:"retry_count"`
	LastSuccess pgtype.Timestamptz `json:"last_success"`
	LastFailure pgtype.Timestamptz `json:"last_failure"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WebhookDelivery struct {
	ID           string             `json:"id"`
	WebhookID    string             `json:"webhook_id"`
	EventType    string             `json:"event_type"`
	Payload      string             `json:"payload"`
	ResponseCode pgtype.Int4        `json:"response_code"`
	ResponseBody pgtype.Text        `json:"response_body"`
	Success      bool               `json:"success"`
	AttemptCount int32              `json:"attempt_count"`
	NextRetry    pgtype.Timestamptz `json:"next_retry"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
