// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Name        string             `json:"name"`
	KeyHash     string             `json:"key_hash"`
	KeyPrefix   string             `json:"key_prefix"`
	Scopes      []string           `json:"scopes"`
	Environment string             `json:"environment"`
	IsActive    bool               `json:"is_active"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Domain struct {
	ID                 string             `json:"id"`
	UserID             string             `json:"user_id"`
	DomainName         string             `json:"domain_name"`
	Status             string             `json:"status"`
	VerifiedForSending bool               `json:"verified_for_sending"`
	DkimTokens         []string           `json:"dkim_tokens"`
	DkimStatus         string             `json:"dkim_status"`
	MailFromDomain     pgtype.Text        `json:"mail_from_domain"`
	MailFromStatus     pgtype.Text        `json:"mail_from_status"`
	Region             string             `json:"region"`
	LastVerifiedAt     pgtype.Timestamptz `json:"last_verified_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Email struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	FromAddress  string             `json:"from_address"`
	ToAddresses  []string           `json:"to_addresses"`
	CcAddresses  []string           `json:"cc_addresses"`
	BccAddresses []string           `json:"bcc_addresses"`
	Subject      string             `json:"subject"`
	Body         pgtype.Text        `json:"body"`
	Html         pgtype.Text        `json:"html"`
	Status       string             `json:"status"`
	ProviderID   pgtype.Text        `json:"provider_id"`
	Metadata     []byte             `json:"metadata"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	MessageID    pgtype.Text        `json:"message_id"`
	InReplyTo    pgtype.Text        `json:"in_reply_to"`
}

type EmailAttachment struct {
	ID            string             `json:"id"`
	EmailID       string             `json:"email_id"`
	Filename      string             `json:"filename"`
	ContentType   string             `json:"content_type"`
	S3Key         string             `json:"s3_key"`
	SizeBytes     int64              `json:"size_bytes"`
	ScanStatus    string             `json:"scan_status"`
	ScanCheckedAt pgtype.Timestamptz `json:"scan_checked_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
