// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Name        string             `json:"name"`
	KeyHash     string             `json:"key_hash"`
	KeyPrefix   string             `json:"key_prefix"`
	Scopes      []string           `json:"scopes"`
	Environment string             `json:"environment"`
	IsActive    bool               `json:"is_active"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Domain struct {
	ID                 string             `json:"id"`
	UserID             string             `json:"user_id"`
	DomainName         string             `json:"domain_name"`
	Status             string             `json:"status"`
	VerifiedForSending bool               `json:"verified_for_sending"`
	DkimTokens         []string           `json:"dkim_tokens"`
	DkimStatus         string             `json:"dkim_status"`
	MailFromDomain     pgtype.Text        `json:"mail_from_domain"`
	MailFromStatus     pgtype.Text        `json:"mail_from_status"`
	Region             string             `json:"region"`
	LastVerifiedAt     pgtype.Timestamptz `json:"last_verified_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type SuppressionList struct {
	EmailHash       string             `json:"email_hash"`
	UserID          string             `json:"user_id"`
	Reason          string             `json:"reason"`
	BounceType      pgtype.Text        `json:"bounce_type"`
	SourceMessageID pgtype.Text        `json:"source_message_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID         string             `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	Role       string             `json:"role"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ExternalID pgtype.Text        `json:"external_id"`
}
