// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reputation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFlaggedUsers = `-- name: CountFlaggedUsers :one
SELECT COUNT(*)::INTEGER as total
FROM user_reputation
WHERE is_flagged = TRUE AND is_suspended = FALSE
`

func (q *Queries) CountFlaggedUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countFlaggedUsers)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countIncidentsByUser = `-- name: CountIncidentsByUser :one
SELECT 
    COUNT(*) FILTER (WHERE incident_type = 'bounce_hard')::INTEGER as hard_bounces,
    COUNT(*) FILTER (WHERE incident_type = 'bounce_soft')::INTEGER as soft_bounces,
    COUNT(*) FILTER (WHERE incident_type = 'complaint')::INTEGER as complaints,
    COUNT(*) FILTER (WHERE incident_type IN ('bounce_hard', 'bounce_soft') AND created_at > NOW() - INTERVAL '30 days')::INTEGER as bounces_30d,
    COUNT(*) FILTER (WHERE incident_type = 'complaint' AND created_at > NOW() - INTERVAL '30 days')::INTEGER as complaints_30d
FROM reputation_incidents
WHERE user_id = $1
`

type CountIncidentsByUserRow struct {
	HardBounces   int32 `json:"hard_bounces"`
	SoftBounces   int32 `json:"soft_bounces"`
	Complaints    int32 `json:"complaints"`
	Bounces30d    int32 `json:"bounces_30d"`
	Complaints30d int32 `json:"complaints_30d"`
}

func (q *Queries) CountIncidentsByUser(ctx context.Context, userID string) (CountIncidentsByUserRow, error) {
	row := q.db.QueryRow(ctx, countIncidentsByUser, userID)
	var i CountIncidentsByUserRow
	err := row.Scan(
		&i.HardBounces,
		&i.SoftBounces,
		&i.Complaints,
		&i.Bounces30d,
		&i.Complaints30d,
	)
	return i, err
}

const ensureUserReputation = `-- name: EnsureUserReputation :exec
INSERT INTO user_reputation (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsureUserReputation(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, ensureUserReputation, userID)
	return err
}

const getUserReputation = `-- name: GetUserReputation :one
SELECT id, user_id, total_bounces, hard_bounces, soft_bounces, complaints, bounces_30d, complaints_30d, suspension_score, is_flagged, flagged_at, flagged_reason, is_suspended, suspended_at, suspended_by, suspension_reason, created_at, updated_at FROM user_reputation WHERE user_id = $1
`

func (q *Queries) GetUserReputation(ctx context.Context, userID string) (UserReputation, error) {
	row := q.db.QueryRow(ctx, getUserReputation, userID)
	var i UserReputation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalBounces,
		&i.HardBounces,
		&i.SoftBounces,
		&i.Complaints,
		&i.Bounces30d,
		&i.Complaints30d,
		&i.SuspensionScore,
		&i.IsFlagged,
		&i.FlaggedAt,
		&i.FlaggedReason,
		&i.IsSuspended,
		&i.SuspendedAt,
		&i.SuspendedBy,
		&i.SuspensionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReputationIncident = `-- name: InsertReputationIncident :exec
INSERT INTO reputation_incidents (
    id, user_id, incident_type, message_id, recipient_email_hash,
    bounce_type, bounce_subtype, complaint_feedback_type, diagnostic_code
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertReputationIncidentParams struct {
	ID                    string      `json:"id"`
	UserID                string      `json:"user_id"`
	IncidentType          string      `json:"incident_type"`
	MessageID             string      `json:"message_id"`
	RecipientEmailHash    string      `json:"recipient_email_hash"`
	BounceType            pgtype.Text `json:"bounce_type"`
	BounceSubtype         pgtype.Text `json:"bounce_subtype"`
	ComplaintFeedbackType pgtype.Text `json:"complaint_feedback_type"`
	DiagnosticCode        pgtype.Text `json:"diagnostic_code"`
}

func (q *Queries) InsertReputationIncident(ctx context.Context, arg InsertReputationIncidentParams) error {
	_, err := q.db.Exec(ctx, insertReputationIncident,
		arg.ID,
		arg.UserID,
		arg.IncidentType,
		arg.MessageID,
		arg.RecipientEmailHash,
		arg.BounceType,
		arg.BounceSubtype,
		arg.ComplaintFeedbackType,
		arg.DiagnosticCode,
	)
	return err
}

const listFlaggedUserReputations = `-- name: ListFlaggedUserReputations :many
SELECT ur.id, ur.user_id, ur.total_bounces, ur.hard_bounces, ur.soft_bounces, ur.complaints, ur.bounces_30d, ur.complaints_30d, ur.suspension_score, ur.is_flagged, ur.flagged_at, ur.flagged_reason, ur.is_suspended, ur.suspended_at, ur.suspended_by, ur.suspension_reason, ur.created_at, ur.updated_at, u.email as user_email, u.name as user_name
FROM user_reputation ur
JOIN users u ON ur.user_id = u.id
WHERE ur.is_flagged = TRUE AND ur.is_suspended = FALSE
ORDER BY ur.suspension_score DESC
LIMIT $1 OFFSET $2
`

type ListFlaggedUserReputationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListFlaggedUserReputationsRow struct {
	ID               string             `json:"id"`
	UserID           string             `json:"user_id"`
	TotalBounces     int32              `json:"total_bounces"`
	HardBounces      int32              `json:"hard_bounces"`
	SoftBounces      int32              `json:"soft_bounces"`
	Complaints       int32              `json:"complaints"`
	Bounces30d       int32              `json:"bounces_30d"`
	Complaints30d    int32              `json:"complaints_30d"`
	SuspensionScore  pgtype.Numeric     `json:"suspension_score"`
	IsFlagged        bool               `json:"is_flagged"`
	FlaggedAt        pgtype.Timestamptz `json:"flagged_at"`
	FlaggedReason    pgtype.Text        `json:"flagged_reason"`
	IsSuspended      bool               `json:"is_suspended"`
	SuspendedAt      pgtype.Timestamptz `json:"suspended_at"`
	SuspendedBy      pgtype.Text        `json:"suspended_by"`
	SuspensionReason pgtype.Text        `json:"suspension_reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	UserEmail        string             `json:"user_email"`
	UserName         string             `json:"user_name"`
}

func (q *Queries) ListFlaggedUserReputations(ctx context.Context, arg ListFlaggedUserReputationsParams) ([]ListFlaggedUserReputationsRow, error) {
	rows, err := q.db.Query(ctx, listFlaggedUserReputations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlaggedUserReputationsRow
	for rows.Next() {
		var i ListFlaggedUserReputationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalBounces,
			&i.HardBounces,
			&i.SoftBounces,
			&i.Complaints,
			&i.Bounces30d,
			&i.Complaints30d,
			&i.SuspensionScore,
			&i.IsFlagged,
			&i.FlaggedAt,
			&i.FlaggedReason,
			&i.IsSuspended,
			&i.SuspendedAt,
			&i.SuspendedBy,
			&i.SuspensionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserEmail,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReputationIncidents = `-- name: ListReputationIncidents :many
SELECT id, user_id, incident_type, message_id, recipient_email_hash, bounce_type, bounce_subtype, complaint_feedback_type, diagnostic_code, created_at FROM reputation_incidents
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListReputationIncidentsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListReputationIncidents(ctx context.Context, arg ListReputationIncidentsParams) ([]ReputationIncident, error) {
	rows, err := q.db.Query(ctx, listReputationIncidents, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReputationIncident
	for rows.Next() {
		var i ReputationIncident
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IncidentType,
			&i.MessageID,
			&i.RecipientEmailHash,
			&i.BounceType,
			&i.BounceSubtype,
			&i.ComplaintFeedbackType,
			&i.DiagnosticCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suspendUserReputation = `-- name: SuspendUserReputation :exec
UPDATE user_reputation SET
    is_suspended = TRUE,
    suspended_at = NOW(),
    suspended_by = $2,
    suspension_reason = $3,
    updated_at = NOW()
WHERE user_id = $1
`

type SuspendUserReputationParams struct {
	UserID           string      `json:"user_id"`
	SuspendedBy      pgtype.Text `json:"suspended_by"`
	SuspensionReason pgtype.Text `json:"suspension_reason"`
}

func (q *Queries) SuspendUserReputation(ctx context.Context, arg SuspendUserReputationParams) error {
	_, err := q.db.Exec(ctx, suspendUserReputation, arg.UserID, arg.SuspendedBy, arg.SuspensionReason)
	return err
}

const unsuspendUserReputation = `-- name: UnsuspendUserReputation :exec
UPDATE user_reputation SET
    is_suspended = FALSE,
    is_flagged = FALSE,
    suspended_at = NULL,
    suspended_by = NULL,
    suspension_reason = NULL,
    flagged_at = NULL,
    flagged_reason = NULL,
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) UnsuspendUserReputation(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, unsuspendUserReputation, userID)
	return err
}

const updateUserReputationStats = `-- name: UpdateUserReputationStats :exec
UPDATE user_reputation SET
    total_bounces = $2,
    hard_bounces = $3,
    soft_bounces = $4,
    complaints = $5,
    bounces_30d = $6,
    complaints_30d = $7,
    suspension_score = $8,
    is_flagged = $9,
    flagged_at = CASE WHEN $9 AND NOT is_flagged THEN NOW() ELSE flagged_at END,
    flagged_reason = $10,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserReputationStatsParams struct {
	UserID          string         `json:"user_id"`
	TotalBounces    int32          `json:"total_bounces"`
	HardBounces     int32          `json:"hard_bounces"`
	SoftBounces     int32          `json:"soft_bounces"`
	Complaints      int32          `json:"complaints"`
	Bounces30d      int32          `json:"bounces_30d"`
	Complaints30d   int32          `json:"complaints_30d"`
	SuspensionScore pgtype.Numeric `json:"suspension_score"`
	IsFlagged       bool           `json:"is_flagged"`
	FlaggedReason   pgtype.Text    `json:"flagged_reason"`
}

func (q *Queries) UpdateUserReputationStats(ctx context.Context, arg UpdateUserReputationStatsParams) error {
	_, err := q.db.Exec(ctx, updateUserReputationStats,
		arg.UserID,
		arg.TotalBounces,
		arg.HardBounces,
		arg.SoftBounces,
		arg.Complaints,
		arg.Bounces30d,
		arg.Complaints30d,
		arg.SuspensionScore,
		arg.IsFlagged,
		arg.FlaggedReason,
	)
	return err
}
