// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: suppression.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSuppressionsByUser = `-- name: CountSuppressionsByUser :one
SELECT COUNT(*) FROM suppression_list WHERE user_id = $1
`

func (q *Queries) CountSuppressionsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppressionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredSuppressions = `-- name: DeleteExpiredSuppressions :execrows
DELETE FROM suppression_list 
WHERE expires_at IS NOT NULL AND expires_at < NOW()
`

func (q *Queries) DeleteExpiredSuppressions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSuppressions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSuppressionByHash = `-- name: DeleteSuppressionByHash :exec
DELETE FROM suppression_list WHERE email_hash = $1
`

func (q *Queries) DeleteSuppressionByHash(ctx context.Context, emailHash string) error {
	_, err := q.db.Exec(ctx, deleteSuppressionByHash, emailHash)
	return err
}

const getSuppressionByHash = `-- name: GetSuppressionByHash :one
SELECT email_hash, user_id, reason, bounce_type, source_message_id, expires_at, created_at FROM suppression_list WHERE email_hash = $1
`

func (q *Queries) GetSuppressionByHash(ctx context.Context, emailHash string) (SuppressionList, error) {
	row := q.db.QueryRow(ctx, getSuppressionByHash, emailHash)
	var i SuppressionList
	err := row.Scan(
		&i.EmailHash,
		&i.UserID,
		&i.Reason,
		&i.BounceType,
		&i.SourceMessageID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertSuppression = `-- name: InsertSuppression :exec
INSERT INTO suppression_list (email_hash, user_id, reason, bounce_type, source_message_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (email_hash) DO UPDATE SET
    reason = EXCLUDED.reason,
    bounce_type = EXCLUDED.bounce_type,
    source_message_id = EXCLUDED.source_message_id,
    expires_at = EXCLUDED.expires_at,
    created_at = NOW()
`

type InsertSuppressionParams struct {
	EmailHash       string             `json:"email_hash"`
	UserID          string             `json:"user_id"`
	Reason          string             `json:"reason"`
	BounceType      pgtype.Text        `json:"bounce_type"`
	SourceMessageID pgtype.Text        `json:"source_message_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertSuppression(ctx context.Context, arg InsertSuppressionParams) error {
	_, err := q.db.Exec(ctx, insertSuppression,
		arg.EmailHash,
		arg.UserID,
		arg.Reason,
		arg.BounceType,
		arg.SourceMessageID,
		arg.ExpiresAt,
	)
	return err
}

const listActiveSuppressions = `-- name: ListActiveSuppressions :many
SELECT email_hash, user_id, reason, bounce_type, expires_at, created_at
FROM suppression_list 
WHERE expires_at IS NULL OR expires_at > NOW()
`

type ListActiveSuppressionsRow struct {
	EmailHash  string             `json:"email_hash"`
	UserID     string             `json:"user_id"`
	Reason     string             `json:"reason"`
	BounceType pgtype.Text        `json:"bounce_type"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActiveSuppressions(ctx context.Context) ([]ListActiveSuppressionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSuppressions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSuppressionsRow
	for rows.Next() {
		var i ListActiveSuppressionsRow
		if err := rows.Scan(
			&i.EmailHash,
			&i.UserID,
			&i.Reason,
			&i.BounceType,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppressionsByUser = `-- name: ListSuppressionsByUser :many
SELECT email_hash, reason, bounce_type, expires_at, created_at
FROM suppression_list 
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSuppressionsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListSuppressionsByUserRow struct {
	EmailHash  string             `json:"email_hash"`
	Reason     string             `json:"reason"`
	BounceType pgtype.Text        `json:"bounce_type"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSuppressionsByUser(ctx context.Context, arg ListSuppressionsByUserParams) ([]ListSuppressionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSuppressionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuppressionsByUserRow
	for rows.Next() {
		var i ListSuppressionsByUserRow
		if err := rows.Scan(
			&i.EmailHash,
			&i.Reason,
			&i.BounceType,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
