// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: unsubscribe.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUnsubscribeBatch = `-- name: CheckUnsubscribeBatch :many
SELECT email_hash FROM unsubscribe_list 
WHERE user_id = $1 AND email_hash = ANY($2::text[])
`

type CheckUnsubscribeBatchParams struct {
	UserID  string   `json:"user_id"`
	Column2 []string `json:"column_2"`
}

// Check multiple email hashes for a user in a single query
func (q *Queries) CheckUnsubscribeBatch(ctx context.Context, arg CheckUnsubscribeBatchParams) ([]string, error) {
	rows, err := q.db.Query(ctx, checkUnsubscribeBatch, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email_hash string
		if err := rows.Scan(&email_hash); err != nil {
			return nil, err
		}
		items = append(items, email_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnsubscribesByUser = `-- name: CountUnsubscribesByUser :one
SELECT COUNT(*) FROM unsubscribe_list WHERE user_id = $1
`

func (q *Queries) CountUnsubscribesByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnsubscribesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUnsubscribe = `-- name: DeleteUnsubscribe :exec
DELETE FROM unsubscribe_list 
WHERE user_id = $1 AND email_hash = $2
`

type DeleteUnsubscribeParams struct {
	UserID    string `json:"user_id"`
	EmailHash string `json:"email_hash"`
}

func (q *Queries) DeleteUnsubscribe(ctx context.Context, arg DeleteUnsubscribeParams) error {
	_, err := q.db.Exec(ctx, deleteUnsubscribe, arg.UserID, arg.EmailHash)
	return err
}

const getUnsubscribeByUserAndHash = `-- name: GetUnsubscribeByUserAndHash :one
SELECT id, user_id, email_hash, source_email_id, source, created_at FROM unsubscribe_list 
WHERE user_id = $1 AND email_hash = $2
`

type GetUnsubscribeByUserAndHashParams struct {
	UserID    string `json:"user_id"`
	EmailHash string `json:"email_hash"`
}

func (q *Queries) GetUnsubscribeByUserAndHash(ctx context.Context, arg GetUnsubscribeByUserAndHashParams) (UnsubscribeList, error) {
	row := q.db.QueryRow(ctx, getUnsubscribeByUserAndHash, arg.UserID, arg.EmailHash)
	var i UnsubscribeList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailHash,
		&i.SourceEmailID,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const insertUnsubscribe = `-- name: InsertUnsubscribe :exec
INSERT INTO unsubscribe_list (id, user_id, email_hash, source_email_id, source)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, email_hash) DO NOTHING
`

type InsertUnsubscribeParams struct {
	ID            string      `json:"id"`
	UserID        string      `json:"user_id"`
	EmailHash     string      `json:"email_hash"`
	SourceEmailID pgtype.Text `json:"source_email_id"`
	Source        string      `json:"source"`
}

func (q *Queries) InsertUnsubscribe(ctx context.Context, arg InsertUnsubscribeParams) error {
	_, err := q.db.Exec(ctx, insertUnsubscribe,
		arg.ID,
		arg.UserID,
		arg.EmailHash,
		arg.SourceEmailID,
		arg.Source,
	)
	return err
}

const listAllUnsubscribes = `-- name: ListAllUnsubscribes :many
SELECT user_id, email_hash FROM unsubscribe_list
`

type ListAllUnsubscribesRow struct {
	UserID    string `json:"user_id"`
	EmailHash string `json:"email_hash"`
}

// For cache sync on startup
func (q *Queries) ListAllUnsubscribes(ctx context.Context) ([]ListAllUnsubscribesRow, error) {
	rows, err := q.db.Query(ctx, listAllUnsubscribes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUnsubscribesRow
	for rows.Next() {
		var i ListAllUnsubscribesRow
		if err := rows.Scan(&i.UserID, &i.EmailHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsubscribesByUser = `-- name: ListUnsubscribesByUser :many
SELECT id, email_hash, source_email_id, source, created_at
FROM unsubscribe_list 
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUnsubscribesByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListUnsubscribesByUserRow struct {
	ID            string             `json:"id"`
	EmailHash     string             `json:"email_hash"`
	SourceEmailID pgtype.Text        `json:"source_email_id"`
	Source        string             `json:"source"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUnsubscribesByUser(ctx context.Context, arg ListUnsubscribesByUserParams) ([]ListUnsubscribesByUserRow, error) {
	rows, err := q.db.Query(ctx, listUnsubscribesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnsubscribesByUserRow
	for rows.Next() {
		var i ListUnsubscribesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.EmailHash,
			&i.SourceEmailID,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
