// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, role, api_key_hash, api_key_prefix, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, email, name, role, api_key_hash, api_key_prefix, is_active, created_at, updated_at
`

type CreateUserParams struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	ApiKeyHash   pgtype.Text        `json:"api_key_hash"`
	ApiKeyPrefix pgtype.Text        `json:"api_key_prefix"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.ApiKeyHash,
		arg.ApiKeyPrefix,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.ApiKeyHash,
		&i.ApiKeyPrefix,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT id, email, name, role, api_key_prefix, is_active, created_at, updated_at
FROM users WHERE api_key_hash = $1 AND is_active = true
`

type GetUserByAPIKeyRow struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	ApiKeyPrefix pgtype.Text        `json:"api_key_prefix"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByAPIKey(ctx context.Context, apiKeyHash pgtype.Text) (GetUserByAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, apiKeyHash)
	var i GetUserByAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.ApiKeyPrefix,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, role, api_key_prefix, is_active, created_at, updated_at
FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	ApiKeyPrefix pgtype.Text        `json:"api_key_prefix"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.ApiKeyPrefix,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, role, api_key_prefix, is_active, created_at, updated_at
FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	ApiKeyPrefix pgtype.Text        `json:"api_key_prefix"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.ApiKeyPrefix,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    email = $2,
    name = $3,
    role = $4,
    is_active = $5,
    updated_at = $6
WHERE id = $1
RETURNING id, email, name, role, api_key_hash, api_key_prefix, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	IsActive  bool               `json:"is_active"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.IsActive,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.ApiKeyHash,
		&i.ApiKeyPrefix,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAPIKey = `-- name: UpdateUserAPIKey :exec
UPDATE users SET api_key_hash = $2, api_key_prefix = $3, updated_at = NOW() WHERE id = $1
`

type UpdateUserAPIKeyParams struct {
	ID           string      `json:"id"`
	ApiKeyHash   pgtype.Text `json:"api_key_hash"`
	ApiKeyPrefix pgtype.Text `json:"api_key_prefix"`
}

func (q *Queries) UpdateUserAPIKey(ctx context.Context, arg UpdateUserAPIKeyParams) error {
	_, err := q.db.Exec(ctx, updateUserAPIKey, arg.ID, arg.ApiKeyHash, arg.ApiKeyPrefix)
	return err
}
