// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: webhook.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (id, user_id, name, url, secret_hash, events, is_active, retry_count, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, name, url, secret_hash, events, is_active, retry_count, last_success, last_failure, created_at, updated_at
`

type CreateWebhookParams struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	Name       string             `json:"name"`
	Url        string             `json:"url"`
	SecretHash string             `json:"secret_hash"`
	Events     []string           `json:"events"`
	IsActive   bool               `json:"is_active"`
	RetryCount int32              `json:"retry_count"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Url,
		arg.SecretHash,
		arg.Events,
		arg.IsActive,
		arg.RetryCount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.SecretHash,
		&i.Events,
		&i.IsActive,
		&i.RetryCount,
		&i.LastSuccess,
		&i.LastFailure,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (id, webhook_id, event_type, payload, response_code, response_body, success, attempt_count, next_retry, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, webhook_id, event_type, payload, response_code, response_body, success, attempt_count, next_retry, created_at
`

type CreateWebhookDeliveryParams struct {
	ID           string             `json:"id"`
	WebhookID    string             `json:"webhook_id"`
	EventType    string             `json:"event_type"`
	Payload      string             `json:"payload"`
	ResponseCode pgtype.Int4        `json:"response_code"`
	ResponseBody pgtype.Text        `json:"response_body"`
	Success      bool               `json:"success"`
	AttemptCount int32              `json:"attempt_count"`
	NextRetry    pgtype.Timestamptz `json:"next_retry"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.ID,
		arg.WebhookID,
		arg.EventType,
		arg.Payload,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.Success,
		arg.AttemptCount,
		arg.NextRetry,
		arg.CreatedAt,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventType,
		&i.Payload,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.Success,
		&i.AttemptCount,
		&i.NextRetry,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteWebhook, id)
	return err
}

const getActiveWebhooksByEvent = `-- name: GetActiveWebhooksByEvent :many
SELECT id, user_id, name, url, events, is_active, retry_count, last_success, last_failure, created_at, updated_at
FROM webhooks WHERE is_active = true AND $1 = ANY(events)
`

type GetActiveWebhooksByEventRow struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Name        string             `json:"name"`
	Url         string             `json:"url"`
	Events      []string           `json:"events"`
	IsActive    bool               `json:"is_active"`
	RetryCount  int32              `json:"retry_count"`
	LastSuccess pgtype.Timestamptz `json:"last_success"`
	LastFailure pgtype.Timestamptz `json:"last_failure"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActiveWebhooksByEvent(ctx context.Context, events []string) ([]GetActiveWebhooksByEventRow, error) {
	rows, err := q.db.Query(ctx, getActiveWebhooksByEvent, events)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveWebhooksByEventRow
	for rows.Next() {
		var i GetActiveWebhooksByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.Events,
			&i.IsActive,
			&i.RetryCount,
			&i.LastSuccess,
			&i.LastFailure,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, user_id, name, url, events, is_active, retry_count, last_success, last_failure, created_at, updated_at
FROM webhooks WHERE id = $1
`

type GetWebhookByIDRow struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Name        string             `json:"name"`
	Url         string             `json:"url"`
	Events      []string           `json:"events"`
	IsActive    bool               `json:"is_active"`
	RetryCount  int32              `json:"retry_count"`
	LastSuccess pgtype.Timestamptz `json:"last_success"`
	LastFailure pgtype.Timestamptz `json:"last_failure"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWebhookByID(ctx context.Context, id string) (GetWebhookByIDRow, error) {
	row := q.db.QueryRow(ctx, getWebhookByID, id)
	var i GetWebhookByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.Events,
		&i.IsActive,
		&i.RetryCount,
		&i.LastSuccess,
		&i.LastFailure,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookDeliveriesByWebhookID = `-- name: GetWebhookDeliveriesByWebhookID :many
SELECT id, webhook_id, event_type, payload, response_code, response_body, success, attempt_count, next_retry, created_at FROM webhook_deliveries WHERE webhook_id = $1 ORDER BY created_at DESC LIMIT $2
`

type GetWebhookDeliveriesByWebhookIDParams struct {
	WebhookID string `json:"webhook_id"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) GetWebhookDeliveriesByWebhookID(ctx context.Context, arg GetWebhookDeliveriesByWebhookIDParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, getWebhookDeliveriesByWebhookID, arg.WebhookID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventType,
			&i.Payload,
			&i.ResponseCode,
			&i.ResponseBody,
			&i.Success,
			&i.AttemptCount,
			&i.NextRetry,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhooksByUserID = `-- name: GetWebhooksByUserID :many
SELECT id, user_id, name, url, events, is_active, retry_count, last_success, last_failure, created_at, updated_at
FROM webhooks WHERE user_id = $1 ORDER BY created_at DESC
`

type GetWebhooksByUserIDRow struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Name        string             `json:"name"`
	Url         string             `json:"url"`
	Events      []string           `json:"events"`
	IsActive    bool               `json:"is_active"`
	RetryCount  int32              `json:"retry_count"`
	LastSuccess pgtype.Timestamptz `json:"last_success"`
	LastFailure pgtype.Timestamptz `json:"last_failure"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWebhooksByUserID(ctx context.Context, userID string) ([]GetWebhooksByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getWebhooksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWebhooksByUserIDRow
	for rows.Next() {
		var i GetWebhooksByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.Events,
			&i.IsActive,
			&i.RetryCount,
			&i.LastSuccess,
			&i.LastFailure,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks SET
    name = $2,
    url = $3,
    events = $4,
    is_active = $5,
    retry_count = $6,
    last_success = $7,
    last_failure = $8,
    updated_at = $9
WHERE id = $1
RETURNING id, user_id, name, url, secret_hash, events, is_active, retry_count, last_success, last_failure, created_at, updated_at
`

type UpdateWebhookParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Url         string             `json:"url"`
	Events      []string           `json:"events"`
	IsActive    bool               `json:"is_active"`
	RetryCount  int32              `json:"retry_count"`
	LastSuccess pgtype.Timestamptz `json:"last_success"`
	LastFailure pgtype.Timestamptz `json:"last_failure"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Events,
		arg.IsActive,
		arg.RetryCount,
		arg.LastSuccess,
		arg.LastFailure,
		arg.UpdatedAt,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.SecretHash,
		&i.Events,
		&i.IsActive,
		&i.RetryCount,
		&i.LastSuccess,
		&i.LastFailure,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
