// Package autoresponse provides detection of auto-generated email replies
// such as Out-of-Office messages, vacation responders, and mailer-daemon bounces.
package autoresponse

import (
	"regexp"
	"strings"
)

// Type represents the kind of auto-response detected.
type Type string

const (
	TypeNone         Type = ""
	TypeOOO          Type = "ooo"           // Out of Office / Vacation
	TypeAutoReply    Type = "auto-reply"    // Generic auto-reply
	TypeMailerDaemon Type = "mailer-daemon" // Bounce / NDR
	TypeMailingList  Type = "mailing-list"  // Mailing list message
)

// Info contains the results of auto-response detection.
type Info struct {
	IsAutoResponse bool
	Type           Type
	Reason         string // Which header/pattern triggered detection
}

// subjectPatterns matches common auto-reply subject prefixes (case-insensitive).
var subjectPatterns = regexp.MustCompile(`(?i)^(Auto:|Automatic reply|Out of Office|OOO:|Abwesenheit|Absence|Vacation|Away:)`)

// Detector checks email headers for auto-response indicators.
type Detector struct{}

// NewDetector creates a new auto-response detector.
func NewDetector() *Detector {
	return &Detector{}
}

// Detect analyzes email headers and returns detection results.
// Headers should be provided as a map where keys are header names and values are slices of header values.
func (d *Detector) Detect(headers map[string][]string) Info {
	// Normalize header keys to lowercase for consistent lookup
	normalized := make(map[string][]string, len(headers))
	for k, v := range headers {
		normalized[strings.ToLower(k)] = v
	}

	// 1. RFC 3834: Auto-Submitted header (highest priority)
	if vals := normalized["auto-submitted"]; len(vals) > 0 {
		val := strings.ToLower(strings.TrimSpace(vals[0]))
		if val != "no" && val != "" {
			autoType := TypeAutoReply
			if strings.Contains(val, "auto-replied") {
				autoType = TypeOOO
			}
			return Info{
				IsAutoResponse: true,
				Type:           autoType,
				Reason:         "Auto-Submitted: " + vals[0],
			}
		}
	}

	// 2. Microsoft Exchange: X-Auto-Response-Suppress
	if vals := normalized["x-auto-response-suppress"]; len(vals) > 0 && vals[0] != "" {
		return Info{
			IsAutoResponse: true,
			Type:           TypeAutoReply,
			Reason:         "X-Auto-Response-Suppress: " + vals[0],
		}
	}

	// 3. Legacy auto-reply headers
	for _, header := range []string{"x-autoreply", "x-autorespond", "x-autogenerated"} {
		if vals := normalized[header]; len(vals) > 0 && vals[0] != "" {
			return Info{
				IsAutoResponse: true,
				Type:           TypeAutoReply,
				Reason:         header + ": " + vals[0],
			}
		}
	}

	// 4. Precedence header
	if vals := normalized["precedence"]; len(vals) > 0 {
		val := strings.ToLower(strings.TrimSpace(vals[0]))
		switch val {
		case "bulk", "junk", "list":
			return Info{
				IsAutoResponse: true,
				Type:           TypeMailingList,
				Reason:         "Precedence: " + val,
			}
		case "auto_reply":
			return Info{
				IsAutoResponse: true,
				Type:           TypeAutoReply,
				Reason:         "Precedence: auto_reply",
			}
		}
	}

	// 5. Empty Return-Path indicates bounce
	if vals := normalized["return-path"]; len(vals) > 0 {
		val := strings.TrimSpace(vals[0])
		if val == "<>" || val == "" {
			return Info{
				IsAutoResponse: true,
				Type:           TypeMailerDaemon,
				Reason:         "Return-Path: <> (empty)",
			}
		}
	}

	// 6. Mailing list indicators
	if vals := normalized["list-id"]; len(vals) > 0 && vals[0] != "" {
		return Info{
			IsAutoResponse: true,
			Type:           TypeMailingList,
			Reason:         "List-Id present",
		}
	}
	if vals := normalized["list-unsubscribe"]; len(vals) > 0 && vals[0] != "" {
		return Info{
			IsAutoResponse: true,
			Type:           TypeMailingList,
			Reason:         "List-Unsubscribe present",
		}
	}

	// 7. X-Failed-Recipients indicates bounce/NDR
	if vals := normalized["x-failed-recipients"]; len(vals) > 0 && vals[0] != "" {
		return Info{
			IsAutoResponse: true,
			Type:           TypeMailerDaemon,
			Reason:         "X-Failed-Recipients present",
		}
	}

	// 8. From address checks (mailer-daemon, postmaster)
	if vals := normalized["from"]; len(vals) > 0 {
		from := strings.ToLower(vals[0])
		if strings.Contains(from, "mailer-daemon") || strings.Contains(from, "postmaster@") {
			return Info{
				IsAutoResponse: true,
				Type:           TypeMailerDaemon,
				Reason:         "From: " + vals[0],
			}
		}
	}

	// 9. Subject pattern matching (fallback heuristic)
	if vals := normalized["subject"]; len(vals) > 0 {
		if subjectPatterns.MatchString(vals[0]) {
			return Info{
				IsAutoResponse: true,
				Type:           TypeOOO,
				Reason:         "Subject pattern: " + vals[0],
			}
		}
	}

	return Info{IsAutoResponse: false}
}
