// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emailapi/api/internal/dns (interfaces: ValidatorInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_dns.go -package=mocks github.com/emailapi/api/internal/dns ValidatorInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dns "github.com/emailapi/api/internal/dns"
	gomock "go.uber.org/mock/gomock"
)

// MockValidatorInterface is a mock of ValidatorInterface interface.
type MockValidatorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorInterfaceMockRecorder
	isgomock struct{}
}

// MockValidatorInterfaceMockRecorder is the mock recorder for MockValidatorInterface.
type MockValidatorInterfaceMockRecorder struct {
	mock *MockValidatorInterface
}

// NewMockValidatorInterface creates a new mock instance.
func NewMockValidatorInterface(ctrl *gomock.Controller) *MockValidatorInterface {
	mock := &MockValidatorInterface{ctrl: ctrl}
	mock.recorder = &MockValidatorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidatorInterface) EXPECT() *MockValidatorInterfaceMockRecorder {
	return m.recorder
}

// ValidateRecords mocks base method.
func (m *MockValidatorInterface) ValidateRecords(ctx context.Context, expected []dns.ExpectedRecord) *dns.ValidationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRecords", ctx, expected)
	ret0, _ := ret[0].(*dns.ValidationResult)
	return ret0
}

// ValidateRecords indicates an expected call of ValidateRecords.
func (mr *MockValidatorInterfaceMockRecorder) ValidateRecords(ctx, expected any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRecords", reflect.TypeOf((*MockValidatorInterface)(nil).ValidateRecords), ctx, expected)
}
